###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM  = nompicomm
EOS      =   eos_idealgas
HYDRO    =   hydro
DENSITY  =   density
ENTROPY  = noentropy
MAGNETIC =   magnetic
GRAVITY  = nogravity
FORCING  =   forcing
PSCALAR  =   pscalar_nolog

FOURIER  =   fourier_fftpack
POWER    =   power_spectrum

PARTICLES  =   particles_potential
