###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM   = nompicomm

HYDRO     = nohydro
DENSITY   = nodensity
ENTROPY   = noentropy
MAGNETIC  =   magnetic
MAGNETIC_MEANFIELD  =   magnetic/meanfield
RADIATION = noradiation
PSCALAR   = nopscalar

VISCOSITY = noviscosity
GRAVITY   = nogravity
FORCING   = noforcing
SHEAR     = noshear

SPECIAL   = special/meanfield_alpm
