###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM   = nompicomm
GLOBAL    = noglobal

HYDRO     =   hydro
DENSITY   =   density
ENTROPY   = noentropy
MAGNETIC  =   magnetic
RADIATION = noradiation
PSCALAR   = nopscalar

GRAVITY   =   gravity_simple
FORCING   = noforcing
SHEAR     =   shear

DUSTDENSITY  =   dustdensity
DUSTVELOCITY =   dustvelocity
