###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM   =   mpicomm

#================================
# Please uncomment one IO option:
#================================
IO        =   io_dist
#--------------------------------
#IO        =   io_hdf5
#================================

HYDRO     = nohydro
DENSITY   = nodensity
ENTROPY   = noentropy
MAGNETIC  = nomagnetic
RADIATION = noradiation
PSCALAR   = nopscalar

GRAVITY   = nogravity
FORCING   = noforcing
SHEAR     = noshear
VISCOSITY = noviscosity
EOS       = noeos

POINTMASSES = pointmasses

REAL_PRECISION=double
