###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM      = nompicomm
GLOBAL       = noglobal

HYDRO        =   hydro
DENSITY      =   density
ENTROPY      = noentropy
MAGNETIC     = nomagnetic
RADIATION    = noradiation
PSCALAR      = nopscalar

GRAVITY      = nograv
SELFGRAVITY  =   selfgravity
POISSON      =   poisson
FORCING      = noforcing
SHEAR        =   shear
VISCOSITY    =   viscosity

DUSTDENSITY  = nodustdensity
DUSTVELOCITY = nodustvelocity

PARTICLES    = noparticles

FOURIER      =   fourier_fftpack

FFLAGS_GENERAL=-r8
CFLAGS_GENERAL=-DDOUBLE_PRECISION
