###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM     = nompicomm
HYDRO       =   hydro
GRAVITY     = nogravity
DENSITY     =   density
ENTROPY     = noentropy
MAGNETIC    = nomagnetic
FORCING     = noforcing
SHOCK       = noshock
SELFGRAVITY =   selfgravity
POISSON     =   poisson
VISCOSITY   =   viscosity

FOURIER     =   fourier_fftpack
POWER       = nopower_spectrum
