###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM      =   mpicomm_double

HYDRO        =   hydro
DENSITY      =   density
ENTROPY      = noentropy
MAGNETIC     = nomagnetic
RADIATION    = noradiation
PSCALAR      = nopscalar

GRAVITY      = nogravity
SELFGRAVITY  =   selfgravity
POISSON      =   poisson
FORCING      = noforcing
SHEAR        =   shear
VISCOSITY    =   viscosity

DUSTDENSITY  = nodustdensity
DUSTVELOCITY = nodustvelocity

PARTICLES    = noparticles

FOURIER      =   fourier_fftpack


# Use double precision
REAL_PRECISION = double

