###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM   = mpicomm
VISCOSITY = noviscosity
EOS       = noeos
SPECIAL   = special/debug_output_times

# uncomment below to run on GPU
# GPU = gpu_astaroth
