#!/bin/sh
#$Id$
#
#  Examples:
#     ./pc_copy_VAR_procN_shift 1023 512 dir1 dir2
#  Used for restarting with a deeper box (from nz=1024 to 1536)

for i in $(seq $1 -1 0)
do

  j=$(( $i + $2 ))
  echo "cp $3/data/proc$i/var.dat $4/data/proc$j/var.dat"
  cp $3/data/proc$i/var.dat $4/data/proc$j/var.dat

done
