#!/bin/csh
#
#  $Id: pc_newrun 9993 2008-10-22 07:38:25Z boris.dintrans $
#
#  Usage:
#    pc_newscan scan_newname [scan_newdir]
#
#  assume that one is in the old directory
#
if ($#argv == 2) then
  newname=$1
  newdir=$2'/'$1
  olddir=`pwd`
else
  newname=$1
  newdir='../'$1
  olddir=`pwd`
endif
#
echo $olddir
echo $newdir
#
mkdir $newdir
cd $newdir
ls
#
mkdir bin idl templates
cd $olddir
#
pc_newrun master $newdir/master
#
cp bin/* $newdir/bin
cp idl/* $newdir/idl
cp templates/* $newdir/templates
#
#  check in everything (hope you are online!)
#
cd $newdir
cd ..
cvs add $newname
cd $newname
cvs add bin idl templates
#
cd bin
cvs add *
#
cd ../templates
cvs add *
#
cd ../master
cvsci_run
#
