#!/bin/csh
#
#  $Id: pc_newrun 9993 2008-10-22 07:38:25Z boris.dintrans $
#
#  Usage:
#    pc_newscan scan_newname [scan_newdir]
#
#  assume that one is in the old directory
#  $newname is the name of the new directory, but without full path
#
set olddir=$cwd
set newname=$1
#
#  next, determine full path
#  If no extra argument is given, assume that it is located next to $cwd
#  Then, go into the parent directory of new run
#
if ($#argv == 2) then
  cd $2
else
  cd ..
endif
#
#  make new directory name there, go into it, and set $newdir
#
mkdir $1
cd $1
set newdir=$cwd
#
#  make new directories there
#
mkdir bin idl templates
#
#  goto olddir and begin populating content of newdir from here
#
cd $olddir
echo
echo "we should now be in olddir: do pwd"
pwd
echo
echo "check that newdir is ok"
echo $newdir
echo
echo "pc_newrun $olddir/master $newdir/master"
pc_newrun $olddir/master $newdir/master
#
cp bin/* $newdir/bin
cp idl/* $newdir/idl
cp templates/* $newdir/templates
#
#  check in everything (hope you are online!)
#
cd $newdir
cd ..
cvs add $newname
cd $newname
cvs add bin idl templates
#
cd bin
cvs add *
#
cd ../templates
cvs add *
#
cd ../master
cvsci_run
#
