#!/bin/csh
#
#  $Id$
#
#  Runs pc_tsnap (to get time of snapshot) for all var.dat files
#  If a number is given as argument it runs pc_tsnap for all VAR files
#
if ($#argv == 1) then
  pc_tsnap data/proc*/VAR$1 | sort -nk 1.10
else
  pc_tsnap data/proc*/var.dat | sort -nk 1.10
endif
