#!/bin/csh
#
#  $Id$
#
#  Runs tsnap (to get time of snapshot) for all var.dat files
#  If a number is given as argument it runs tsnap for all VAR files
#
if ($#argv == 1) then
  tsnap data/proc*/VAR$1 | sort -nk 1.10
else
  tsnap data/proc*/var.dat | sort -nk 1.10
endif
