###  -*-Makefile-*-  (for Emacs)    vim:set filetype=make:  (for vim)
###
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM   =   mpicomm

DENSITY   = nodensity
HYDRO     =   hydro
MAGNETIC  =   bfield

INITIAL_CONDITION  =   alfven_waves
IMPLICIT_DIFFUSION =   implicit_diffusion

REAL_PRECISION = double
