###  -*-Makefile-*-  (for Emacs)    vim:set filetype=make:  (for vim)
###
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM   =   mpicomm

DENSITY   = nodensity
HYDRO     =   hydro
MAGNETIC  =   bfield

INITIAL_CONDITION  =   initial_condition/alfven_wave
IMPLICIT_DIFFUSION =   implicit_diffusion
FOURIER            =   fourier_fftpack

REAL_PRECISION = double
