###  -*-Makefile-*-  (for Emacs)    vim:set filetype=make:  (for vim)
###
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM   =   mpicomm

DENSITY   = nodensity
HYDRO     =   hydro
MAGNETIC  =   magnetic

REAL_PRECISION = double
