record_types={
    'id_block_persistent':(2000,'i'),
    'random_seeds'       :(1   ,'i'),
    'shear_delta_y'      :(320 ,'d'),
    'hydro_tphase'       :(280 ,'d'),
    'hydro_phase1'       :(281 ,'d'),
    'hydro_phase2'       :(282 ,'d'),
    'hydro_tsforce'      :(284 ,'d'),
    'hydro_location'     :(285 ,'d'),
    'hydro_ampl'         :(286 ,'d'),
    'hydro_wavenumber'   :(287 ,'d'),
    'ism_t_next_old'     :(250 ,'d'),
    'ism_pos_next_old'   :(251 ,'d'),
    'ism_bold_mass'      :(252 ,'d'),
    'ism_t_next_sni'     :(253 ,'d'),
    'ism_t_next_snii'    :(254 ,'d'),
    'ism_x_cluster'      :(255 ,'d'),
    'ism_y_cluster'      :(256 ,'d'),
    'ism_z_cluster'      :(260 ,'d'),
    'ism_t_cluster'      :(261 ,'d'),
    'ism_toggle_sni'     :(257 ,'i'),
    'ism_toggle_snii'    :(258 ,'i'),
    'ism_snrs'           :(259 ,'d'),
    'ism_toggle_old'     :(1001,'d'),
    'ism_snrs_old'       :(1002,'d'),
    'forcing_location'   :(270 ,'d'),
    'forcing_tsforce'    :(271 ,'d'),
    'magnetic_phase'     :(311 ,'d'),
    'magnetic_ampl'      :(312 ,'d'),
}
