###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM   = nompicomm
HYDRO     =   hydro
DENSITY   =   density
ENTROPY   =   entropy
EOS       =   eos_idealgas
MAGNETIC  =   magnetic
RADIATION = noradiation
FORCING   =   forcing
