###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM   =   mpicomm
HYDRO     =   hydro
DENSITY   =   density
MAGNETIC  =   magnetic
FORCING   = noforcing
EOS       =   eos_idealgas
FOURIER   =   fourier_fftpack
POWER     =   power_spectrum
#POISSON   =   poisson
REAL_PRECISION = double
GPU       =   gpu_astaroth
MULTITHREADING=openmp
RUNTIME_COMPILATION = on
