###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM   =   mpicomm
HYDRO     =   hydro
DENSITY   =   density
ENTROPY   =   entropy
MAGNETIC  =   magnetic
RADIATION =   radiation_ray
EOS       =   eos_idealgas
SHOCK     = noshock
FORCING   = noforcing
GRAVITY   = nogravity
FOURIER   =   fourier_fftpack
POWER     =   power_spectrum
REAL_PRECISION = double
