###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM   =   mpicomm

INITIAL_CONDITION = init_delta

IMPLICIT_DIFFUSION =   implicit_diffusion

VISCOSITY = noviscosity
EOS       = noeos

MAGNETIC  =   magnetic

REAL_PRECISION = double
