###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM=nompicomm
GRAVITY=nogravity
FORCING=noforcing
ENTROPY=noentropy
MAGNETIC=magnetic
VISCOSITY=noviscosity
HYDRO=nohydro
EOS=noeos
DENSITY=nodensity
FOURIER=fourier_fftpack
POWER=power_spectrum
SPECIAL = special/klein_gordon special/disp_current special/gravitational_waves_hTXk
REAL_PRECISION=double
