###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM   = nompicomm
GLOBAL    = noglobal

HYDRO     =   hydro
DENSITY   =   density
ENTROPY   = noentropy
MAGNETIC  = nomagnetic
RADIATION = noradiation
PSCALAR   = nopscalar

GRAVITY   = nograv
FORCING   = noforcing
SHEAR     = noshear
VISCOSITY =   viscosity

DUSTDENSITY  = nodustdensity
DUSTVELOCITY = nodustvelocity

PARTICLES =   particles_dust
