### $Id$
### Machine Specific Makefile for modular pencil code
### 
### The appropriate Makefile will be chosen from the config tree and included during at compile time 
### 

## Uncomment this line to inherit the Makefile in the parent directory
include ../Makefile




FC=f95
FFLAGS=-O3
F90FLAGS=-u -tpp7
F90FLAGS=
LDMPI=
CFLAGS=-O3 -DFUNDERSC=1 -Wall
F77=$(FC)

