###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM=nompicomm
GRAVITY=nogravity
FORCING=noforcing
ENTROPY=noentropy
MAGNETIC=nomagnetic
VISCOSITY=noviscosity
HYDRO=nohydro
EOS=noeos
DENSITY=nodensity
#FOURIER=fourier_fftpack
#POWER=power_spectrum
#SPECIAL = special/lorentz_gauge
#SPECIAL = special/disp_current
#SPECIAL = special/backreact_infl special/disp_current special/lorentz_gauge
#SPECIAL = special/backreact_infl special/disp_current special/gravitational_waves_hTXk
SPECIAL = special/klein_gordon
#SPECIAL = special/chiral_mhd special/gravitational_waves_hTXk
#SPECIAL =  special/backreact_infl special/gravitational_waves_hTXk
#SPECIAL =  special/gravitational_waves_hTXk
#SPECIAL = special/lorentz_gauge
REAL_PRECISION=double
