###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

LDMPI=-lmpi
FSTD=-std=f2003
MPICOMM   =   mpicomm
IO        =   io_dist
GPU       =   gpu_astaroth
HYDRO     =   hydro
DENSITY   =   density
MAGNETIC  =   magnetic
ENTROPY   =   entropy
EOS       =   eos_idealgas

#FORCING   =   forcing
SHEAR     = noshear
TRANSPILATION=on
RUNTIME_COMPILATION=on
REAL_PRECISION = double
