###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

LDMPI=-lmpi
MPICOMM   = nompicomm
IO        =   io_dist
GLOBAL    = noglobal
FFT       = nofft
FFTPACK   = nofftpack

HYDRO     =   hydro
DENSITY   =   density
ENTROPY   =   entropy
MAGNETIC  = nomagnetic
RADIATION = noradiation
PSCALAR   = nopscalar

EOS       = eos_idealgas
GRAVITY   =   grav_z
FORCING   = noforcing
SHEAR     = noshear
