#+TITLE: Git Best Practises


#+begin_abstract
#+LaTeX: \noindent%
Tips and recommendations for using Git with the Pencil code.
#+end_abstract


* Operative Summary

  Here is the bottom line of this document.

  1. Decide whether you want to rebase or merge your local changes into
     upstream (typically the /origin/master/ branch).

     a. Rebase: Use '=git pull --rebase=' to get upstream changes into you
        local tracking branch (typically /master/).

     b. Merge: Do /not/ merge upstream into your tracking branch like this:
        #+BEGIN_SRC sh
        git merge origin/master  # DON'T!
        #+END_SRC
        because that breaks the SVN bridge and makes it quite difficult to
        understand the repository's topology.

        Instead, merge your changes into upstream, either manually or
        using '=git pc reverse-merge='.

  2. Think about using feature branches for logic units that cover more
     than a few commits.


* Prerequisites

  We need a few simple concepts for the discussion to follow.


** What is Git?

   Git is a flexible version-control system that is well-suited for
   software development, be it with a centralized server (Github, in our
   case), or in a completely decentralized setting.


** What is a Git repository?

   A Git repository is a set of unique commits that form a
   [[https://en.wikipedia.org/wiki/Directed_acyclic_graph][directed acyclic graph]] (DAG) like this:
   #+begin_example
     A---B---C---D---E---F--- master
          \     /     \
           F---G       H---I--- feature
   #+end_example

   We say that E is a /child/ of D, and that D has two
   /parents/, C and G.
   The /ancestors/ of D consists of A, B, C, F, and G.
   The /descendants/ of D are E, F, H, and I.

   If you know how to read this diagram, you know enough about DAGs for
   our purposes.[fn:1]


[fn:1]You get extra credits if you can answer the question “Which of the
   commits A, E and F belong to branch /feature/?”


*** What is a commit?

    A commit typically represents a state of the file tree (the directory
    tree you get by checking out a revision), together with its complete
    commit ancestry.
    So you get different commit ids (represented as hexadecimal SHA1 hash
    codes) if you
    - commit a change, commit the inverse of that change, and commit the
      original change again;
    - change the commit message of your last commit (with '=git commit
      --amend=');
    - take some part of the commit graph and attach it somewhere else
      ('=git rebase=');
    - make any change to a commit that is an ancestor of the commit in
      question.


** The different layers[?] of a Git repository's state

   1. Upstream [there could be several, but not for us]
   2. Tracking branch
   3. Index
   4. File system

   → Many combinations that can conflict
   But don't worry, it is not hard to sort them all out.


** Merging and rebasing

*** What is merging?
    <<Merge>>

    A /merge/ commit adds a new connection to parts of the Git graph.
    For example, if we have the following situation
    #+begin_example
      A---B---C--- master
           \
            F---G--- feature
    #+end_example
    and want to bring the changes from branch /feature/ to /master/, we
    can merge /feature/ into /master/ and get
    #+begin_example
      A---B---C---D--- master
           \     /
            F---G--- feature
    #+end_example

    In the pure DAG sense, the two parents C and G of the merge commit D
    are completely equivalent, but for reasons discussed [[below]], we want to
    make sure we merge /feature/ into /master/ (so C is the /first parent/
    and G is the /second parent/), not the other way around.


*** What is rebasing?
    <<Rebase>>

    In the example above, we have a second option to bring the feature
    branch's changes into master, by creating new commits that contain
    those changes:
    #+begin_example
      A---B---C---D---F'---G'--- master, feature
    #+end_example
    Immediately after this, both /master/ and /feature/ point to the same
    commit G', but this may change in the future, e.g.
    #+begin_example
      A---B---C---D---F'---G'---H--- master
                            \
                             I--- feature
    #+end_example

    Rebasing is not an exclusive option.
    Even if you routinely rebase your local changes, you will want to
    merge longer-lived feature branches.


*** Pros and cons

    Here is the decision matrix for merging vs. rebasing

    | Criterion                 | Merge        | Rebase           |
    |---------------------------+--------------+------------------|
    | Resulting graph structure | More complex | Simpler          |
    | History                   | Preserved    | Modified         |
    | Safety                    | Safer        | Less safe [fn:2] |

    In short, use merging when you are afraid – [[What to do when you think you're lost][but you needn't be afraid]].


[fn:2] Less safe in the sense that conflicts can cause you to end up
    in a detached-head state.


**** Graph structure

     Every merge commit increases the connectivity of the commit graph by
     one[fn:3].


[fn:3] Or even more than one, in the case of an /octopus merge/.
     But those are somewhat exotic.


**** Rewriting history

     In our rebase example above, the commits F and G were transformed
     into F' and G'.
     In the simplest case, both sets of commits represent exactly the same
     difference of the file tree.
     But if you had to fix conflicts, this is no longer the case, and you
     appear to have lost the original change G by pretending that you were
     applying a change G' in the first place.[fn:4]


[fn:4] But of course this is not true: you can use [[git reflog]]
     to go back to your original changes.
     And you should no longer be interested in the original change once
     the new version gets part of the Git narrative[?].


     Once you embrace the idea that you can change history, you can use it
     to write meaningful commit messages while you are in the right set
     of mind (i.e. /before/ you test your changes, because after testing
     it is harder to remember what you were doing in the first place).
     Or you can rewrite history to fix a recent commit (code and message),
     or to combine commits in order to get a more readable history.

**** The worst thing that can happen

     If you have conflicts, rebasing can bring your sandbox [explain that
     name, or use another word] into a state where you are not on any
     branch (/detached head/).
     This is not really something to worry about:
     Just fix the conflicts and do '=git rebase --continue=' to finish the
     rebase; and in case you get lost, do '=git rebase --abort=' and start
     afresh.
     Even if you get completely lost and resort to measures like
     '=git reset=', [[What to do when you think you're lost][you needn't be afraid]] to lose history.


* Best practices

** Don't merge upstream into your tracking branch
   [… except when it makes sense]

   Suppose you just started developing code on /master/.
   Your branches look like this (`A' and `B' are commits, the `o' is just
   a visual connector):
   #+begin_example
     --A---B-----  origin/master (remote branch)
            \
             o---  master (local tracking branch)
   #+end_example

   The tracking branch exists only on your local computer, and you modify
   it by adding commits, rebasing them, etc.

   The /remote branch/ also exists only on your computer.
   It represents what is known about a branch called /master/ on the
   server and serves for synchronization with the server.
   You cannot directly commit to this branch.

   \bigskip

   Now you commit some changes X, Y to your local tracking branch:
   #+begin_example
     --A---B----------  origin/master
            \
             X---Y----  master
   #+end_example
   and want to push them to the server.
   If the server is still at commit B, this will result in
   #+begin_example
     --A---B---X---Y-----  origin/master
                    \
                     o---  master
   #+end_example

   However, if somebody has committed changes to the server before you
   push, you will get an error message:
   #+begin_example
     To [...]
      ! [rejected]        master -> master (fetch first)
     error: failed to push some refs to [...]
   #+end_example
   followed by some explanatory text.

   Before you can fix the problem, you need to =git fetch= to update the
   remote branch:
   #+begin_example
     --A---B---C---D---E--  origin/master
            \
             X---Y--------  master
   #+end_example

   Your aim is to bring the two lines of development together, and you can
   either do this [[Rebase][using rebase]], or [[Merge][using merge]].

   Rebasing is straight-forward, you run
   #+begin_src sh
     git rebase origin/master
   #+end_src
   , if necessary deal with conflicts (that will temporarily throw your
   repository into a headless state) and end up with
   #+begin_example
     --A---B---C---D---E-----------  origin/master
                        \
                         X'---Y'---  master
   #+end_example
   You have changed your commits by turning them into descendants of E (and
   possibly by including solutions for conflicts) and you can now push to
   get
   #+begin_example
     --A---B---C---D---E---X'---Y'----  origin/master
                                 \
                                  o---  master
   #+end_example
   As you can see, this approach gives you a linear history similar to
   what you know from /Subversion/.

   Alternatively, we can merge the two branches together.
   It is tempting to just call (after the =git fetch=)
   #+begin_src sh
     git merge origin/master  # DON'T DO THIS
   #+end_src
   which would give you the following repository structure
   #+begin_example
     --A---B---C---D---E-----  origin/master
            \           \
             X-----Y-----M---  master
   #+end_example
   This doesn't look so bad, but when you push /master/, you will get
   #+begin_example
     --A---B---C---D---E---M----  origin/master
            \             / \
             X-----------Y   o--  master
   #+end_example

   Topologically, that is exactly what we want.
   But there is more to a git repository than pure topology of the
   directed acyclic graph: there is an order in parentage.
   Y is the /first parent/ of the merge commit M, while E is the /second
   parent/:[fn:5]
   #+begin_example
                         2
     --A---B---C---D---E---M-----  origin/master
            \             /1\
             X-----------Y   o---  master
   #+end_example
   This can be rearranged as
   #+begin_example
                     1
     --A---B---X---Y---M-----  origin/master
            \         /2 \
             C---D---E   o---  master
   #+end_example
   and indeed this is what many tools will show you.[fn:6]
   For example, commands like =gitk --first-parent= (or simply =git log
   --first-parent=), you give you
   #+begin_example
     --A---B---X---Y---M-----  origin/master
                \     / \
                         o---  master
   #+end_example
   which suggests that the main chain (= first-parent lineage) of commits
   on the server has disruptively changed from
   #+begin_example
     --A---B---C---D---E-----
   #+end_example
   to
   #+begin_example
     --A---B---X---Y---M-----
   #+end_example

   Given that the SVN bridge probably has to rely on first-parent lineage
   between commits, it is pretty obvious that such a reinterpretation
   leads to a new SVN repository structure that is not compatible with
   what we had before.
     Hence, it is not surprising that such merges cause troubles with the
   SVN bridge:
   #+begin_example
     $ svn commit <file>
     svn: E160024: Transmission failed (Details follow):
     svn: E160024: resource out of date; try updating
   #+end_example


[fn:5]My notation in the graph is adopted from
   [[http://git-blame.blogspot.de/2015/03/fun-with-non-fast-forward.html][this quite readable discussion]].


[fn:6]Including the [[https://github.com/pencil-code/pencil-code/network][GitHub network graph]], gitk (to some extent) and the
GitHub SVN bridge.


   \bigskip

   So is it really wrong to merge?
   Not if you merge the right way around.
   You need to create a merge commit where the latest upstream commit (E
   in our example) is the first parent, and the tracking-branch commit (Y)
   is the second parent.

   How to do this is left as an exercise to the reader.
   It is not very tricky, but for convenience we have a =git-pc= command
   #+begin_src sh
     git pc reverse-merge origin-master  # DO THIS INSTEAD
   #+end_src
   that gives you exactly the desired structure:
   #+begin_example
                         1
     --A---B---C---D---E---M-----  origin/master
            \             /2\
             X-----------Y   o---  master
   #+end_example

   Aside from problems with the SVN bridge, merging the right way around
   will also lead to a much more meaningful history.
   Consider the following real-life example:[fn:25]
   #+begin_example
     Simo Tuomisto      M─┐ Merge branch 'master' of https://github.com/pencil-
     Philippe Bourdin   │ o Probably 94aaf8acef156847ab319efee38fc46212dcbff8 f
     Philippe Bourdin   │ o Fixed stupid mistake from df97a8ab42d4f04bf3e6c4f12
     Wladimir Lyra      │ o Break if other used than spherical
     mrheinhardt        │ o corrected bug in communication for gravity adap
     Axel Brandenburg   │ o replaced Wlad's caltech email by his gmail
     Jørgen Aarnes      │ M─┐ Merge branch 'master' of https://github.com/penci
     Axel Brandenburg   │ │ o moved commented out line about 0d-tests/reactive_
     Jørgen Aarnes      │ o │ smaller changes in config file for specific syste
     Philippe Bourdin   │ o─┘ This was overseen by the automatic script.
     Philippe Bourdin   │ o This was overseen by the automatic script.
     mrheinhardt        │ o gravity_after_boundary added
     mrheinhardt        │ o gravity_after_boundary added
     Simo Tuomisto      o │ Much improved version of pc_meanfield_collect.
     mrheinhardt        o─┘ diagnostics idiag_Kkramersmz, idiag_Kkramersmx
     mrheinhardt        o added parameter n_adjust_sphersym: if > 0 after e
   #+end_example

   which is way more readable in the form

   #+begin_example
     Simo Tuomisto      M───┐ Merge a few commits into master
     Philippe Bourdin   o   │ Probably 94aaf8acef156847ab319efee38fc46212dcbff8 f
     Philippe Bourdin   o   │ Fixed stupid mistake from df97a8ab42d4f04bf3e6c4f12
     Wladimir Lyra      o   │ Break if other used than spherical
     mrheinhardt        o   │ corrected bug in communication for gravity adap
     Axel Brandenburg   o   │ replaced Wlad's caltech email by his gmail
     Jørgen Aarnes      M─┐ │ Merge temporary branch into master
     Axel Brandenburg   o │ │ moved commented out line about 0d-tests/reactive_
     Jørgen Aarnes      │ o │ smaller changes in config file for specific syste
     Philippe Bourdin   o─┘ │ This was overseen by the automatic script.
     Philippe Bourdin   o   │ This was overseen by the automatic script.
     mrheinhardt        o   │ gravity_after_boundary added
     mrheinhardt        o   │ gravity_after_boundary added
     Simo Tuomisto      │   o Much improved version of pc_meanfield_collect.
     mrheinhardt        o───┘ diagnostics idiag_Kkramersmz, idiag_Kkramersmx
     mrheinhardt        o     added parameter n_adjust_sphersym: if > 0 after e
   #+end_example


   #+begin_example
     Chao-Chin Yang            o │ Mac does not like the option -std=f95.
     Iomsn                     o │ Added normalization parameter for the Gaussian profile footpoint driver.
     Iomsn                     o │ Added single dominand polarity as initial condition for the magnetic field.
     Chao-Chin Yang            M─│─┐ Merge branch 'master' of https://github.com/pencil-code/pencil-code
     Iomsn                     │ │ o Added single parasitic polarity as initial condition.
     Chao-Chin Yang            o │ │ Fix a bug in timestep condition in particles_dust.
     Chao-Chin Yang            M─│─┘ Merge branch 'master' of https://github.com/pencil-code/pencil-code
     Nils Erland L. Haugen     │ │ o Make sure that all indices are "sound" for the lognormal initial distribution.
     Nils Erland L. Haugen     │ │ o added diagnostics for mean particle (including the swarm particles) number density in the volume
     Philippe Bourdin          │ │ o Added comment to remind me of removing this block later...
     Philippe Bourdin          │ │ o Finally gives fixes for backwards-compatibility.
     Philippe Bourdin          │ │ o Fixed call without parameters.
     Philippe Bourdin          │ │ o Making interface backwards-compatible for now.
     Philippe Bourdin          │ │ o Fixed the automatically (double-)expanded 'pc_precision' common block.
     Philippe Bourdin          │ │ o Extended 'pc_precision' common block for all routines, because it looks like some scripts (like "
     Chao-Chin Yang            o │ │ Add initial condition 'random' in particles_spin.
     Nils Erland L. Haugen     o─│─┘ Set lzero_upper_kern to make sure no mass is lost.
     mrheinhardt               o │ added parallel reading of binary data; changed find_namelist because of CRAY compiler issue;
     Philippe Bourdin          o │ Extendend consistency checking and adapted to new 'pc_precision' common block structure.
     Philippe Bourdin          o │ Fully redesigned, will enable automatic finding of the configuration, later.
     Philippe Bourdin          o │ Unified formatting.
   #+end_example

   #+begin_example
     Axel Brandenburg          o merged my changes of the Summer in experimental/meanfield.f90 (and checked in incorrectly in the wr
     Philippe Bourdin          o Lets see if the new IO modules work everywhere as expected...
     Frederick Gent            M─┐ Merge branch 'master' of https://github.com/pencil-code/pencil-code
     Philippe Bourdin          │ o We explicitly want to allow missing namelists in "data/param.nml". This should fix all remaining
     Frederick Gent            o │ New sample data to account for correction to chi calc in entropy
     Frederick Gent            M─│─┐ Merge branch 'master' of https://github.com/pencil-code/pencil-code
     Jörn Warnecke             │ o─┘ joern: fixed some errors
     Frederick Gent            M─│─┐ Merge branch 'master' of https://github.com/pencil-code/pencil-code
     Jörn Warnecke             │ o─┘ removed some doubling of some subroutine
     mrheinhardt               │ o preparations for flux-limited diffusion
     mrheinhardt               │ o moved sqrt of characteristic velocity to equ; removed some comments
   #+end_example

   #+begin_example
     Simo Tuomisto             M─┐ Merge branch 'master' of https://github.com/pencil-code/pencil-code
     Frederick Gent            │ o Revised data to account for correction to chi-therm and nu-therm
     Philippe Bourdin          │ o Moved replicated code of 'collect_grid' into Mpicomm, because this is independa
     Philippe Bourdin          │ o Fixed some stupid mistakes in the MPI-IO and simplified error handling.
     Philippe Bourdin          │ o g95 v0.92 will not compile 'file_io_f2003' in its current state, reverting the
     Philippe Bourdin          │ o Bug in gfortran below 4.8 prevents from allocating variable-length strings, put
     Philippe Bourdin          │ o Moved "0d-tests/reactive_particles" to where it belongs.
     Philippe Bourdin          │ o Fixed indentation.
     Philippe Bourdin          │ o Adding the 'corona' autotest one level higher, want to test it with the hourly
     Axel Brandenburg          │ o merged my changes of the Summer in experimental/meanfield.f90 (and checked in i
     Philippe Bourdin          │ o Lets see if the new IO modules work everywhere as expected...
     Frederick Gent            │ M─┐ Merge branch 'master' of https://github.com/pencil-code/pencil-code
     Philippe Bourdin          │ │ o We explicitly want to allow missing namelists in "data/param.nml". This shoul
     Frederick Gent            │ o │ New sample data to account for correction to chi calc in entropy
     Frederick Gent            │ M─│─┐ Merge branch 'master' of https://github.com/pencil-code/pencil-code
     Jörn Warnecke             │ │ o─┘ joern: fixed some errors
     Frederick Gent            │ M─│─┐ Merge branch 'master' of https://github.com/pencil-code/pencil-code
     Jörn Warnecke             │ │ o─┘ removed some doubling of some subroutine
     mrheinhardt               │ │ o MR: preparations for flux-limited diffusion
     mrheinhardt               │ │ o MR: moved sqrt of characteristic velocity to equ; removed some comments
     mrheinhardt               │ │ o MR: sqrt of characteristic velocity moved here
     mrheinhardt               │ │ o MR: preparations for flux-limited diffusion
     Jörn Warnecke             │ │ o joern+MR:More correction for slope limited diffusion
     Iomsn                     │ │ o Make sure to skip nulls which are invalid.
     Iomsn                     │ │ o Updated the default parameter for the field line integration to 'trilinear' i
     Philippe Bourdin          │ │ o The autoexpansion functionality is now integrated in 'pc_autocorrect_config'.
     Philippe Bourdin          │ │ o Added namelist-autoexpansion functionality from 'pc_autoexpand_config'.
     Philippe Bourdin          │ │ o Shorten output on a namelist error.
     Philippe Bourdin          │ │ o Namelist error shall never be wiped out.
     Philippe Bourdin          │ │ o Fixed typo from 55aed70b759fd1908461f61f151380fa52433792.
     Philippe Bourdin          │ │ o Need 'ltolerate_namelist_errors' as global parameter.
     Philippe Bourdin          │ │ o Filtering out no-modules from modules list. Added some more comments.
     Philippe Bourdin          │ │ o Making sure we have no recursive endless loop. Addded some comments.
     Philippe Bourdin          │ │ o Added some comments for documentation.
     Philippe Bourdin          │ │ o Added option '--no-autocorrect' to suppress autocorrection.
     Jörn Warnecke             │ │ o added output and comment for slope limited diffusion
     Philippe Bourdin          │ │ o Formatting.
     Axel Brandenburg          │ │ o added settings for ekhi
     Philippe Bourdin          │ │ o Added 'KEEP_RELOADING' within samples directories.
     Iomsn                     │ │ o Removed redundant code.
     Iomsn                     │ │ o Discard double fixed points.
     Jörn Warnecke             │ │ o joern+MR: more on slope limited diffusion
     Philippe Bourdin          │ │ o 'nu_shock_jump1' was used but not initialized. See also descriptions of bd102
     Philippe Bourdin          │ │ o Removed 'nu_shock_jump1' varible and replaced with actual constant. It is hig
     Philippe Bourdin          │ │ o Removed debug code, sorry.
     mrheinhardt               │ │ o MR: added diffusive fluxes for 1D y and z setups
     mrheinhardt               │ │ o MR: moved calc_diff_flux to sub.f90
     Illa R. Losada            │ │ M─┐ Merge branch 'master' of https://github.com/pencil-code/pencil-code Adding
     Axel Brandenburg          │ │ │ o some corrections/modifications in hillrain
     Axel Brandenburg          │ │ │ o removed 2 unused variables
     Axel Brandenburg          │ │ │ o added Hill vortex rain as forcing
     Axel Brandenburg          │ │ │ o two missing real :: nu_shock_jump1 entered
     Philippe Bourdin          │ │ │ o Do not make a mess if another 'pencil-test' is already running in the very
     Philippe Bourdin          │ │ │ M─┐ Finally fixed the last still broken autotest! 'nu_jump1' was simply not i
     Philippe Bourdin          │ │ │ │ o Finally fixed the last still broken autotest! 'nu_jump1' was simply not i
     Philippe Bourdin          │ │ │ o │ Removed spaces at EOL.
     Jörn Warnecke             │ │ │ o │ More correction and additions for the slope limited diffusion,
     Philippe Bourdin          │ │ │ o │ Moved experimental code to "src/experimental/".
     Philippe Bourdin          │ │ │ o─┘ Removed "array temporaries", see also 2a73f3cea323f8c08d2824f7d5f5003d904
     Philippe Bourdin          │ │ │ o Fixed some "array temporaries", see also 2a73f3cea323f8c08d2824f7d5f5003d90
     Philippe Bourdin          │ │ │ o Added some missing "intent(in)" for 'inear'.
     Philippe Bourdin          │ │ │ o Fixing two runtime-warnings ("An array temporary was created for argument '
     mrheinhardt               │ │ │ o MR: added a phase to enforced vertical shear profile; correction in calcula
     Illa R. Losada            │ │ o │ Adding components of the current helicity tensor.
     Frederick Gent            │ o │ │ thermo hydrostatic equilibrium ISM still under construction
     Frederick Gent            │ o │ │ added sound speed dependent resistivity for ISM turbulence
     Frederick Gent            │ o │ │ Streamline lheatc_chitherm
     Frederick Gent            │ o │ │ Cleaned up duplicate
     Frederick Gent            │ o │ │ Relabelled iheatcool as inetcool
     Frederick Gent            │ o │ │ added comment at top of module
     Frederick Gent            │ o │ │ Added missing term for gradient of chi in thermally dependent conduction
     Frederick Gent            │ o │ │ Completed calculation of density, and magnetic field
     Frederick Gent            │ o │ │ Minor edit to print statement
     Simo Tuomisto             o │ │ │ pc_meanfield_collect: Fixed some bugs and removed line writes
     Simo Tuomisto             M─│─│─│─┐ Merge branch 'master' of https://github.com/pencil-code/pencil-code
     Philippe Bourdin          │ │ │ o─┘ New tool 'pc_autoexpand_config' automatically fills in missing namelists
     Philippe Bourdin          │ │ │ o Fixed error message.
     Philippe Bourdin          │ │ │ o Fixed error message.
     Philippe Bourdin          │ │ │ M─┐ Merge branch 'master' of https://github.com/pencil-code/pencil-code
     Chao-Chin Yang            │ │ │ │ o Prevent t - dt < 0, which sometimes happens.
     Philippe Bourdin          │ │ │ │ o This was presumably debug code and should not be checked in. Joern, pleas
     Jörn Warnecke             │ │ │ │ o more correction for slope limited diffusion
     Jörn Warnecke             │ │ │ │ o minor change to make to code compile again
     mrheinhardt               │ │ │ │ o MR: more corrections for slope-limited diffusion
     mrheinhardt               │ │ │ │ o MR: corrected for use of iFF_char_c: pointer to the slot for characterist
     mrheinhardt               │ │ │ │ o MR: corrected staggered 4th order derivative
     Philippe Bourdin          │ │ │ o │ Fixed missing namelist.
     Philippe Bourdin          │ │ │ o─┘ Removed ugly hack with 'lstart' and introduced new 'lparam_nml' to indica
     Philippe Bourdin          │ │ │ o The idea in e9285e2c3c751f789620646cd15db4edc6d612a0 could not work, becaus
     Philippe Bourdin          │ │ │ o Need to tolerate namelist error for 'param.nml' for backwards-compatibility
     Philippe Bourdin          │ │ │ o Seems we need larger lines...
     Philippe Bourdin          │ │ │ o Formatting.
     Philippe Bourdin          │ │ │ o Added missing namelist.
     Philippe Bourdin          │ │ │ o Need to lower-case also the namelist name provided by the source code.
     Philippe Bourdin          │ │ │ o Formatting.
     mrheinhardt               │ │ │ o MR: some corrections to the slope-limited diffusion scheme
     Philippe Bourdin          │ │ │ o Need to export the new function 'find_namelist' as public.
     Philippe Bourdin          │ │ │ o Added routine to check for the existence of a namelist before actually tryi
     Philippe Bourdin          │ │ │ o Added 'lstreamlines' in order to prevent missing namelist errors for setups
     Philippe Bourdin          │ │ │ o Added forgotten 'lstreamlines', so that the nostreamlines-module will not t
     Philippe Bourdin          │ │ │ o Removed unneeded line.
     Philippe Bourdin          │ │ │ o Added funtion to lower-case a string.
     Philippe Bourdin          │ │ │ o Formatting.
     Philippe Bourdin          │ │ │ o Replaced with proper operators.
     Philippe Bourdin          │ │ │ M─┐ Another annoying merge branch 'master' of https://github.com/pencil-code/
     Frederick Gent            │ │ │ │ M─┐ Merge branch 'master' of https://github.com/pencil-code/pencil-code
     Frederick Gent            │ │ │ │ o │ Removed obsolete i that broke the autotest
     Philippe Bourdin          │ │ │ o │ │ Slowly adapting to the current state of the File_IO modules - still unf
     Philippe Bourdin          │ │ │ o─│─┘ Formatting.
     Dhrubaditya MITRA         │ │ │ o─┘ If the electric field was to be stored as auxiliary, there was a confusio
     Philippe Bourdin          │ │ │ M─┐ Annoying merge branch 'master' of https://github.com/pencil-code/pencil-c
     Jörn Warnecke             │ │ │ │ o some minor correction to slope limited diffusion
     Philippe Bourdin          │ │ │ o │ Added general interface 'mpibcast' for MPI-broadcasts in any types.
     mrheinhardt               │ │ │ o─┘ MR: bug fixed
     Philippe Bourdin          │ │ │ o Same as 51518940fe1b344d98e741bd9925d482a9ee5a97.
     Philippe Bourdin          │ │ │ o This should fix the Norlx51b daily G95 autotest. The problem was that 't_sp
     mrheinhardt               │ │ │ o MR: missing dummy added
     mrheinhardt               │ │ │ o MR: fixed bug
     mrheinhardt               │ │ │ o MR: fixed bug, added missing dummy
     mrheinhardt               │ │ │ o MR: added missing dummies
     Philippe Bourdin          │ │ │ o Removed debug output.
     Jörn Warnecke             │ │ │ o More on characteric velocity
     mrheinhardt               │ │ │ o MR: corrected last commit
     mrheinhardt               │ │ │ o MR: putlnrho for scalar argument added
     Jörn Warnecke             │ │ │ o minor
     Jörn Warnecke             │ │ │ o more on slope limited diffusion
     mrheinhardt               │ │ │ o MR: more for char velocity calc
     mrheinhardt               │ │ │ o MR: more for char velocity calc
     mrheinhardt               │ │ │ o MR: morefor calc of characteriistic velocity
     Iomsn                     │ │ │ o Changed core parallelization from using threads to multiprocessing library.
     Jörn Warnecke             │ │ │ o more stuff for slope limited diffusion
     mrheinhardt               │ │ │ o MR: more for flux-limited diffusion
     Jörn Warnecke             │ │ │ o corrected for the case of using /trimxyz
     Jörn Warnecke             │ │ │ o minor corrections
     Frederick Gent            │ │ │ M─┐ Merge branch 'master' of https://github.com/pencil-code/pencil-code
     mrheinhardt               │ │ │ │ o MR: added 4th order scheme which calculates first derivative on centered
     mrheinhardt               │ │ │ │ o MR: added missing dummy
     Iomsn                     │ │ │ │ o Added  time series to the fixed point finding routine.
     mrheinhardt               │ │ │ │ o MR+JW+FG:More correction to the slope limited diffusion. Still in testing
     Iomsn                     │ │ │ │ o Corrected case for small values of the Jacobian determinand int he null p
     Iomsn                     │ │ │ │ o Import of h5py library is now semi optional. Return warning message.
     Iomsn                     │ │ │ │ o Corrected the sign of the field integration for the spines.
     mrheinhardt               │ │ │ │ o MR: changes for slope-limited diffusion
     Jörn Warnecke             │ │ │ │ o add one comment
     mrheinhardt               │ │ │ │ o MR: prepared for slope-limited diffusion
     mrheinhardt               │ │ │ │ o MR: optimized storage use for slope-limited diffusion
     Philippe Bourdin          │ │ │ │ o Fixed typo.
     Philippe Bourdin          │ │ │ │ o Identical, but more readable code.
     Philippe Bourdin          │ │ │ │ o Fixed computation of the necessary iproc numbers. This should fix Petri's
     Jörn Warnecke             │ │ │ │ o added comment for flux limited diffusion
     Jörn Warnecke             │ │ │ │ o some correction to slope limited diffusion
     Philippe Bourdin          │ │ │ │ o Fixed one error.
     Dhrubaditya MITRA         │ │ │ │ o Includes optional Stokes drag and also the option of running with several
     Dhrubaditya MITRA         │ │ │ │ o The reference file is changed too.
     Dhrubaditya MITRA         │ │ │ │ o New version of the sample this time with particles_radius included.
     Chao-Chin Yang            │ │ │ │ o Fix an indexing error in the boundary condition.
     Chao-Chin Yang            │ │ │ │ o No need to initialize bspline when nygrid > 1.
     mrheinhardt               │ │ │ │ o MR: changes for slope-limited diffusion
     Iomsn                     │ │ │ │ o Added fixed_points to the python init file.
     Iomsn                     │ │ │ │ o Added interpolation routine for compatability with the streamline module.
     Iomsn                     │ │ │ │ o Changed some variable names to conform to conventions.
     Iomsn                     │ │ │ │ o Corrected poincare member.
     Philippe Bourdin          │ │ │ │ o Minor (small letters for function names can be crucial on case-sensitive
     Petri Käpylä              │ │ │ │ o Fix broken IDL read-routines: dimensions need to be read before they can
     Philippe Bourdin          │ │ │ │ o Added inverse of the Alfvén velocity. This allows to compute the Alfvén t
     Philippe Bourdin          │ │ │ │ o Extracted replicated code into separate procedures. Please, someone with
     Philippe Bourdin          │ │ │ │ o Added Alfvén velocity to list of available quantities.
     Philippe Bourdin          │ │ │ │ o Added x- and y-components of the impulse density.
     Iomsn                     │ │ │ │ o Added fixed point finding routine. Needs some fixing to work correctly.
     Iomsn                     │ │ │ │ o Confirming now to POP8 convention.
     Iomsn                     │ │ │ │ o Added/updated tracer writing and reading routine.
     Iomsn                     │ │ │ │ o Added tracers routine into pencilnew.
     Iomsn                     │ │ │ │ o Clean up in the streamline tracer routine.
     Iomsn                     │ │ │ │ o Added streamlinne routines to the new python modules.
     Iomsn                     │ │ │ │ o Check the Jacobian determinant during the null point finding process.
     Chao-Chin Yang            │ │ │ │ o Fix a bug in gentle forcing in selfgravity.
     Jonas Krueger             │ │ │ │ o changed the standard value for the calculation of the sherwood number to
     Iomsn                     │ │ │ │ o Some clean up of the routines.
     Iomsn                     │ │ │ │ o Fixed isse with the connectivity matrix when vertices are deleted.
     Philippe Bourdin          │ │ │ │ o Adapted Sven's 74cb51af7c1208ad6065bd1f03ef9e4dabcbdb23 for the other IO
     Philippe Bourdin          │ │ │ │ o Fixed 74cb51af7c1208ad6065bd1f03ef9e4dabcbdb23, should fix compiling of '
     Philippe Bourdin          │ │ │ │ o With SVN this would not have been possible...
     Philippe Bourdin          │ │ │ │ o I don't really see, why GIT is unable to merge properly... So I need to c
     Philippe Bourdin          │ │ │ │ o No idea what GIT found to be different, here - maybe spaces at EOL?
     Sven Bingert              │ │ │ │ o went back to the old version
     System Administrator      │ │ │ │ M─┐ Update Merge branch 'master' of https://github.com/pencil-code/pencil-c
     Wolfgang Dobler           │ │ │ │ │ o Revert "Make config for Norlx51b work."
     Wolfgang Dobler           │ │ │ │ │ o Use Makefile.src, not Makefile when building with pc_build.
     Wolfgang Dobler           │ │ │ │ │ o Encapsulate 'make' calls in a function.
     Iomsn                     │ │ │ │ │ o Do not trace separatrices if the Jacobian is singular.
     Sven Bingert              │ │ │ │ o │ try to fix for the case when nxcpu=nycpu=nzcpu=1
     Sven Bingert              │ │ │ │ M─│─┐ get new code Merge branch 'master' of https://github.com/pencil-code/
     Sven Bingert              │ │ │ │ o │ │ for testing
     Sven Bingert              │ │ │ │ o │ │ for testing
     Frederick Gent            │ │ │ o │ │ │ modified sample not part of auto test
     Frederick Gent            │ │ │ o │ │ │ New header comment
     Frederick Gent            │ │ │ o │ │ │ Added amplaa to init pars
     Simo Tuomisto             o │ │ │ │ │ │ pc_meanfield_collect: Fixed issue with parallel HDF dataset closing.
     Chao-Chin Yang            o─│─│─│─│─┘ │ Relieve a time step constraint for particles.
     Dhrubaditya MITRA         o │ │ │ │ ┌─┘ Added the missing file. Thanks Matthius.
     mrheinhardt               o │ │ │ │ │ MR: added empty file to fix the auto-test
     Axel Brandenburg          o │ │ │ │ │ Hill vortex added
   #+end_example

   #+begin_example
     Philippe Bourdin          o Code formatting.
     Philippe Bourdin          o Updated.
     Philippe Bourdin          o Removed rather strange and surely outdated comment: MPI libraries have a timeout and will s
     Philippe Bourdin          M─┐ Merge branch 'master' of https://github.com/pencil-code/pencil-code
     Jonas Krueger             │ M─┐ Merge branch 'master' of https://github.com/pencil-code/pencil-code
     Jonas Krueger             │ o │ added the get_diff_coeff_reactants routine to nochemistry
     Philippe Bourdin          o │ │ Added mentions of 'pc_configtest'.
     Philippe Bourdin          o─│─┘ Deleted outdated section.
     Philippe Bourdin          o │ Added full list or actual requirements.
     Philippe Bourdin          o │ Fixing the auto-tests broken from a0da8209f7616612cabe2eca18fd9fe82ec7a409. Jonas: You fo
     mrheinhardt               o │ added output of error code in case of namelist reading error
     mrheinhardt               o │ simplified error messages
     Philippe Bourdin          o │ Fixed the print-out of the sample pars. Thanks Jörn for reporting.
     Iomsn                     o │ Added tracing out of separatrix layers.
     Philippe Bourdin          o │ Trying to fix the 'initial_condition_pars' error message, which follows from a slightly i
     Iomsn                     o │ Aded separatrix class.
     Jonas Krueger             o─┘ added transport fuction for binary diffusion coefficients from chemistry to particles_che
     mrheinhardt               o avoided use of undefined quantities to fix the auto-test
     Philippe Bourdin          o Never try to include something that is not guaranteed to be there.
     Dhrubaditya MITRA         o particles_dust : ldraglaw_purestokes added forcing: sinz as profile for forcing.
   #+end_example

   #+begin_example
     Philippe Bourdin          o Never use hardcoded file units, this is ugly and messy.
     Philippe Bourdin          o Added most important reading routines for "big data".
     Philippe Bourdin          M─┐ Merge branch 'master' of https://github.com/pencil-code/pencil-code
     andreas-schreiber         │ o python code should be stabel in matplotlib and backends now
     andreas-schreiber         │ o BARE YOUR NAMESPACES! Dont ever import modules into higher namespaces. Always import what you
     andreas-schreiber         │ o to do list for new python codes
     Philippe Bourdin          │ o Hello Fred, please check if this works for you. "FSTD" should not be overwritten.
     Philippe Bourdin          o │ Removed unused variable.
     Philippe Bourdin          o │ Formatting.
     Philippe Bourdin          o │ A bit simpler, skip the 'REAL_PRECISION' line.
     Philippe Bourdin          o─┘ This additional script will dynamically extend config files with missing namelist entries (no
     Philippe Bourdin          o Added "data/param.nml" in automatic correction, so that reloading simulation would not complain
     andreas-schreiber         M─┐ Merge branch 'master' of https://github.com/pencil-code/pencil-code
     mrheinhardt               │ o split up an if statement: missing short-circuiting caused the failure of the autotest whe
     Simo Tuomisto             │ o pc_meanfield_collect: Changes to match changes in param_io
     mrheinhardt               │ o avoided undefined initial values in single_ray to calm the auto-test
     Philippe Bourdin          │ M─┐ Why again this??? Merge branch 'master' of https://github.com/pencil-code/pencil-code
     Axel Brandenburg          │ │ o added diagostics of divud2m. Added request for curlo in one diagnostics.
     Axel Brandenburg          │ │ o added straining motion
     Axel Brandenburg          │ │ o added possibility for alpha_zz tensor in spherical geometry
     Boris Dintrans            │ │ o changed the grav_xz forcing (uniform vorticity now)
     Philippe Bourdin          │ o │ Applied new version of 'pc_autocorrect_config' to the corona sample *.in files.
     Philippe Bourdin          │ o │ Target-namelist for renaming a parameter has to be given and will be checked. Identical par
     Philippe Bourdin          │ o │ Formatting of comments.
     mrheinhardt               │ o─┘ initialized gravity in initialize_special explicitly to zero to avoid NaNs (should fix
     mrheinhardt               │ o removed strip_comments and other unneeded stuff; tested
     Philippe Bourdin          │ o Fixed typo in routine name. Removed variable with unexplained name. Fixed error messages to s
   #+end_example

   #+begin_example
     imo Tuomisto              │ │ │ o pc_meanfield_collect: First round of removing old code.
     Simo Tuomisto             │ │ │ o pc_meanfield_collect.f90: Working parallel HDF writing.
     Simo Tuomisto             │ │ │ o Added working parallel hdf file creation.
     Philippe Bourdin          │ │ o │ This was overseen by the automatic script.
     Illa R. Losada            o │ │ │ Changed the default plotting settings to keep and interactive shell.
     Illa R. Losada            M─┘ │ │ Merge branch 'master' of https://github.com/pencil-code/pencil-code
     Frederick Gent            │ o │ │ Reassigned lncoolH as double in module header and removed obsolete comment
     Frederick Gent            │ o │ │ Moved depricated module to interstallar_old.f90 and copied experimental/supernova.f90 to in
     Frederick Gent            │ o │ │ Revised interstellar sample to use new interstellar module and initial_condition
     Frederick Gent            │ o │ │ Updated sample reference and run parameters to match old and new interstellar modules
     Frederick Gent            │ M─│─│─┐ Merge branch 'master' of https://github.com/pencil-code/pencil-code
     Iomsn                     │ │ │ │ o Added option for different pfiles other than pvar.dat.
     Iomsn                     │ │ │ │ o Checks if simulation si double or single precision and adjusts the reading of binary data
     Frederick Gent            │ o │ │ │ Updated record labels to match revised recored types
     Frederick Gent            │ o │ │ │ Fixed fractions
     Frederick Gent            │ o │ │ │ Revised reference data with new and old interstellar modules
     Frederick Gent            │ o │ │ │ Updated sample reference using old interstellar.f90
     Frederick Gent            │ M─│─│─┘ Merge branch 'master' of https://github.com/pencil-code/pencil-code
     Jørgen R. Aarnes          │ │ │ │ o fixed image scaling in make_movie()
     Frederick Gent            │ o │ │ │ Removed obsolete persistent variables, restructured remnants, updated clustering of SN op
     Frederick Gent            │ o │ │ │ Deprecated obsolete ISM record types and added cluster variables
     Frederick Gent            │ M─│─│─┘ Merge branch 'master' of https://github.com/pencil-code/pencil-code
     Frederick Gent            │ o │ │ │ Reformatted in line with special.h
     Frederick Gent            │ o │ │ │ Removed obsolete mass movement routines, integrated cosmic ray injection into existing en
     Frederick Gent            │ o │ │ │ Removed obsolete subroutine to force location
     Frederick Gent            │ o │ │ │ Added auto-test generated files from backwards-compatible/data while omitting source code
     Frederick Gent            │ o │ │ │ Merged z-dependent UV-heating into single sub-routine and deleted obsolete intitial densi
     Illa R. Losada            o │ │ │ │ Adding some options to "Video files and slices" subsection
     Jørgen R. Aarnes          o─│─│─│─┘ small changes to allow for reading 2D-runs
     Axel Brandenburg          o │ │ │ in hydro and magnetic: changed default to lno_second_ampl=.true. (which is the correct choi
     Frederick Gent            M─┘ │ │ Merge branch 'master' of https://github.com/pencil-code/pencil-code
     Piyali Chatterjee         │ M─│─│─┐ Merge branch 'master' of https://github.com/pencil-code/pencil-code
     Piyali Chatterjee         │ o │ │ │ Changed compiler flags for Vilje and Pleiades
     Frederick Gent            o │ │ │ │ Revised reference file ot check modified supernova returns same results
     Frederick Gent            o │ │ │ │ Set parameters to match old interstellar sample results
     Frederick Gent            o │ │ │ │ Removed obsolete damping, added call to cooling functions and tidied initialise
   #+end_example


   #+begin_example
     Graeme R Sarson           o Allow optional advection term in cosmic ray flux equation.
     Graeme R Sarson           o Allow insertion of cosmic ray flux in SNe.  (Still being tested.)
     Philippe Bourdin          o Need to add the actual AVX code generation option.
     Frederick Gent            o Added new files as part of experimental revision of interstellar
     Frederick Gent            M─┐ Merge branch 'master' of https://github.com/pencil-code/pencil-code
     Piyali Chatterjee         │ o EE should be added to varcontent in the aux part not in the main variables part
     Piyali Chatterjee         │ o Added a flag in run.f90 to write dim.dat files again corrected the writing of IDL files def
     Iomsn                     │ o Bug: reading particle files from procs with no particles. Fixed
     Axel Brandenburg          │ o corrected simplified version of chiral fluids
     Frederick Gent            o │ Added comparison sample to check consistency of revised modules with original
     Frederick Gent            M─┘ Merge branch 'master' of https://github.com/pencil-code/pencil-code
     Philippe Bourdin          │ o Updated to use 'mpiifort' instead of 'mpif90' for the Intel configuration.
     Frederick Gent            o │ Revising interstellar module with initial conditions - in progress
     Frederick Gent            o─┘ added host file for Fred's Aalto pc
     Frederick Gent            M─┐ Merge branch 'master' of https://github.com/pencil-code/pencil-code
     Philippe Bourdin          │ o Should keep GIT calm when some auto-test or samples were executed and ignore the automatica
     Frederick Gent            M─│┐ Merge branch 'master' of https://github.com/pencil-code/pencil-code
     Frederick Gent            │ o┘ Added Philippe's compiler
     Frederick Gent            o │ Corrected minor typo
     Frederick Gent            M─┘ Merge branch 'master' of https://github.com/pencil-code/pencil-code Revising interstellar to
     Natalia Babkovskaia       │ o !  Differential for integration is ad*dln(ad). Prepare here dln(ad) factor. !  This assumes c
     Jørgen R. Aarnes          │ o removed incorrect comments and print statements
     Jørgen R. Aarnes          │ o fixed issue with parallelization in line_mirror method
   #+end_example

   #+begin_example
     Axel Brandenburg          │ o added kvectors as initial condition for benchmark
     Axel Brandenburg          │ o removed debug line
     simon                     │ o Minor corrections on the parasitic polarities initial condition. This fixes spurious currents
     Axel Brandenburg          │ o changed ii=cmplx(0.,1.) to ii=(0.,1.) to fix auto-test
     Axel Brandenburg          │ o modal initial condition from file for magnetic field
     Frederick Gent            M─│─┐ Merge branch 'master' of https://github.com/pencil-code/pencil-code
     Philippe Bourdin          │ o─┘ Adapted automatic procdir recognition for the case that no 'var.dat' but a 'VAR#' file is p
     Frederick Gent            o │ Simplified config file
     Frederick Gent            M─┘ Merge branch 'master' of https://github.com/pencil-code/pencil-code
     Iomsn                     │ o Added e3 type driver.
     Frederick Gent            o │ added += to conf file
     Frederick Gent            o─┘ Corrected fred-asus host fiel to compile with mpi
     Axel Brandenburg          o gamma effect added; experimental
     Chao-Chin Yang            o Avoid the case of no density module in get_gas_density().
     Axel Brandenburg          o allowed for possibility of 0-D data
     Nils Erland L. Haugen     o Corrected how the time step due to drag from particles on the gas is calculated when drag law is
     Simo Tuomisto             M─┐ Merge branch 'master' of https://github.com/pencil-code/pencil-code
     Petri Käpylä              │ o Added turbulent heat transport in Kramers heat conduction and diagnostics of entropy squared an
     Simo Tuomisto             o │ Created working Makefile targets.
     Philippe Bourdin          o─┘ Sub-volumes can't be periodic, if they do not cover the full extent in that direction.
     Simo Tuomisto             M─┐ Merge branch 'master' of https://github.com/pencil-code/pencil-code
     Philippe Bourdin          │ o Probably 94aaf8acef156847ab319efee38fc46212dcbff8 fixed the Segmentation Fault previously prese
     Philippe Bourdin          │ o Fixed stupid mistake from df97a8ab42d4f04bf3e6c4f121d2074a0d5decdd.
     Wladimir Lyra             │ o Break if other used than spherical
     mrheinhardt               │ o corrected bug in communication for gravity adaptation; added calc of grav constant from cen
     Axel Brandenburg          │ o replaced Wlad's caltech email by his gmail
     Jørgen Aarnes             │ M─┐ Merge branch 'master' of https://github.com/pencil-code/pencil-code
     Axel Brandenburg          │ │ o moved commented out line about 0d-tests/reactive_particles outside the array to prevent error
     Jørgen Aarnes             │ o │ smaller changes in config file for specific system
     Philippe Bourdin          │ o─┘ This was overseen by the automatic script.
     Philippe Bourdin          │ o This was overseen by the automatic script.
     mrheinhardt               │ o gravity_after_boundary added
     mrheinhardt               │ o gravity_after_boundary added
     Simo Tuomisto             o │ Much improved version of pc_meanfield_collect. Added also analyzers for it.
     mrheinhardt               o─┘ diagnostics idiag_Kkramersmz, idiag_Kkramersmx for horizontally averaged Kramers heat condu
     mrheinhardt               o added parameter n_adjust_sphersym: if > 0 after each n_adjust_sphersym     timesteps the sphe
     mrheinhardt               o introduced dz2_bound in bc_set_div_z and bc_pp_hds_z_iso
     mrheinhardt               o added subroutines meanyz_* for calculating yz averages by proper integration
     mrheinhardt               o calculation of Area_* added
   #+end_example


[fn:25]The output was obtained using =tig=


   \bigskip

   To summarize this section:
   /When developing on /master/, if you cannot directly push your changes
   due to upstream commits, either use /rebase/, or use /git pc
   reverse-merge/./

   Now consider the case where you have made local changes on your
   tracking branch and then =git fetch= finds that in parallel there have
   been changes on the server:
   #+begin_example
     --A---B---C---D---E--  origin/master (remote branch)
            \
             M---N---O------  master (local tracking branch)
   #+end_example


* Feature branches

  - When you are working on one topic and expect more than a
    handful[fn:7] of changes, consider using a /feature branch/.

  - When you are collaborating on a topic with somebody else and your
    changes are not yet ready for the others, use a feature branch.


[fn:7] Even just two or three commits may be enough to go for a feature
branch if that improves the narrative.


  To work with a feature branch, just go to the latest commit of /master/
  (the later you start the branch, the fewer conflicts you will create),

  #+begin_src sh
    git checkout master
    git pull --rebase
  #+end_src
  and create the branch
  #+begin_src sh
    git checkout -b cool-new-feature
  #+end_src

  \bigskip

  If that branch is long-lived, you will want to occasionally merge master
  into it:[fn:8]
  Run
  #+begin_src sh
    git fetch origin
    git stash  # if you have uncommitted local changes
  #+end_src
  to update your knowledge of the server's master branch.

  Then do
  #+begin_src sh
    git checkout master  # check out your local tracking branch …
    git pull --rebase    # … and bring it up to date

    git checkout cool-new-feature
    git merge master     # do the actual merge
  #+end_src
  There are some shorter variants to this procedure. You can use our
  `=git pc=' script like this:
  #+begin_src sh
    git pc ff-update master  # bring master up-to-date
    git merge master         # do the actual merge
  #+end_src
  or you could directly merge the remote branch
  #+begin_src sh
    git merge origin/master
  #+end_src
  although this is less common than merging the local tracking branch.

  After merging, don't forget to
  #+begin_src sh
    git stash pop
  #+end_src
  If you have stashed changes before you merged.

  \bigskip

  When your branch is ready for merging back, you do
  #+begin_src sh
    git checkout master
    git pull --rebase    # brin master up-to-date
    git merge cool-new-feature
    [test]
    git push
  #+end_src

  The topology now looks like this:
  #+begin_example
    --A---B---C---D---E---F---G---H---I---J---K-- master
       \               \             /
        N---O---P---Q---R---S---T---U             feature
  #+end_example

  \bigskip

  What if that push failed due to somebody committing new changes
  upstream?

  No problem.
  We tag the first merge attempt and merge that tag to the updated
  upstream branch:
  #+begin_src sh
    # remember, we are on master
    git push   # fails: "! [rejected] master -> master (fetch first)"

    git tag previous-merge-of-cool-new-feature
    git fetch                       # update origin/master
    git reset --hard origin/master  # update local master branch
    git merge previous-merge-of-cool-new-feature
    [test]
    git push
  #+end_src

  The narrative now says:
  We have tried to merge /cool-new-feature/ into master, but failed to
  push that, so we then merged that first merge into master and pushed.
  That may be more detail than we wanted (and more steps than we
  anticipated), but describes exactly what happened.

  #+begin_example
    --A---B---C---D---E----F-----G----H---I---J---K-- master
       \               \               \     /
        \               \               V---o
         \               \             /
          N---O---P---Q---R---S---T---U             feature
  #+end_example


  \bigskip


  (*More on feature branches from my email*)


[fn:8] This does not violate our rule
`[[Don't merge upstream into your tracking branch][don't merge upstream into your local tracking branch]]'
because the merge commit is on the branch and that makes perfect narrative
sense.


* Put this somewhere

** Advice against setting pull.rebase
        Or consider '=git config --global pull.rebase true=',
        /but remember to do so in every checkout and expect communication
        problems with others/.

** Use gitk (or '=tig=' or some variant of '=git log --graph=')


** Don't panic
   [[https://en.wikipedia.org/wiki/Phrases_from_The_Hitchhiker's_Guide_to_the_Galaxy#Don.27t_Panic][Don't panic]]
   [or /What to do when you think you're lost/]

   Git will try hard to preserve your changes:[fn:9]

   - Any changes you committed will be part of the [[git reflog][/reflog/]] for at least
     two weeks.[fn:10]

   - Uncommitted changes to git-controlled-files will only get overwritten
     if you run one of the commands
     - =git checkout <file-or-directory>=

   - Files unknown to Git will only get lost with
     - =git clean=
     - Again, any non-git commands that change files


[fn:9]There are corner cases where other git commands (like
   =git stash --include-untracked=) call commands like =git clean=, which
   can in principle [[http://blog.icefusion.co.uk/git-stash-can-delete-ignored-files-git-stash-u/][lead to data loss]].
   However, this should only concern files that match your =.gitignore=
   patterns, and if that is the case for any file you care about, you have
   been asking for trouble beforehand.


[fn:10]Unless you explicitly decide otherwise.


   Table \ref{Table:How-to-lose-changes} summarizes this discussion.

#+label: Table:How-to-lose-changes
#+caption: Scatter Plot with Regression Line
   | Changes                                     | How they can get lost                 |
   |---------------------------------------------+---------------------------------------|
   | Changes committed to git                    | Not at all, unless you insist [fn:11]  |
   |---------------------------------------------+---------------------------------------|
   | Uncommitted changes to git-controlled files | =git  t checkout <file-or-directory>= |
   |                                             | =git reset --hard=                    |
   |                                             | Non-git commands                      |
   |---------------------------------------------+---------------------------------------|
   | Files unknown to Git                        | =git clean=                           |
   |                                             | Non-git commands                      |


[fn:11] Leaving relevant Git commits dangling (≈ unused) for more than two
weeks counts as insisting on data loss.


*** I'm almost panicking because I'm afraid something got lost
    [… although I know this is not the case because I stayed away from the
    commands in Table \ref{Table:How-to-lose-changes}]

    Here is how to see almost every change[fn:12] that was ever[fn:13]
    known to git:
    #+begin_src sh
      gitk --reflog --all
      # or
      tig --reflog --all
      # or, without graphics,
      git reflog --all --glob='stash*'
    #+end_src

    If you want to also see dropped stashes, you can use
    #+begin_src sh
      git pc panic -v
    #+end_src


[fn:12] This will not show dropped stashes or stashes older than the last one.


[fn:13] Redefining “ever” = “in the last two weeks” for dangling commits.


   2. <<git reflog>>'=git reflog=' [plus stash] or '=gitk --reflog='
      or '=git pc reflog [-v]='

      Discuss garbage collection:
      Removes old changes that nobody [no commit] is interested in any
      more.
      Unless you deliberately dropped commits, there will be some other
      form of those commits in the perpetual history, and after two weeks
      you wouldn't remember anyway what you thought when writing the first
      version.

** Narrative
   - Telling a story.
     There are several styles of telling stories:
     - Always merge :: chronicler/diary style.
          Include all the nitty-gritty details, failed attempts, etc.
     - Rebase :: letter/novelist style.
          Bring facts into a logical frames and order them

** Why no automatic pull-the-push

   - Integrity: this is a version that has not existed before
     [Hmm, =svn update= does just the pull part, what you push [commit] is
     what you have in your file system.
     Still, pulling in changes may put your working copy into some strange
     state that git can only represent as /detached head \{true?\} …]


** What to avoid

   - Rewrite history that is already on the server
     - Certainly so if it is on /master/
     - But even feature branches can get merged into master

   - Don't push your personal tags [but not so important, we can delete
     them later]


* To do:
  - gitk: How to show unadded files?


* Org configuration                                   :noexport:ARCHIVE:

#+AUTHOR: Wolfgang Dobler
#+EMAIL:
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE: en

##+STARTUP: content
#+STARTUP: showall

##+ARCHIVE: ::* Archive

#+DRAWERS: HIDDEN PROPERTIES CLOCK LOGBOOK
#+PROPERTIES: CLOCK_INTO_DRAWER 2

#+TODO: TODO | DONE WONTFIX

#+OPTIONS: toc:nil
##+OPTIONS: toc:t  tags:not-in-toc
#+OPTIONS: ^:{}
#+OPTIONS: tasks:todo
##+OPTIONS: num:nil
#+OPTIONS: H:4 num:t
##+OPTIONS: \n:nil @:t ::t |:t -:t f:t *:t <:t
##+OPTIONS: TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil

##+EXPORT_SELECT_TAGS: export
##+EXPORT_EXCLUDE_TAGS: noexport

#+LaTeX_CLASS_OPTIONS: [12pt,pdftex]
##+LaTeX_CLASS_OPTIONS: [paralist]
##+LATEX_HEADER: \newcommand{\sectionbreak}{\clearpage}

;; File variables

;; Local Variables:
;;   mode: org
;;   ispell-check-comments: t
;;   coding: utf-8
;;   eval: (flyspell-mode 1)
;;   ispell-local-dictionary: "en_CA"
;; End:

;;
;; LocalWords:


