###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM   =   mpicomm_double
GLOBAL    = noglobal

HYDRO     =   hydro
DENSITY   =   density
ENTROPY   =   entropy
MAGNETIC  = nomagnetic
RADIATION = noradiation
PSCALAR   = nopscalar

GRAVITY   =   gravity_simple
FORCING   = noforcing
SHEAR     =   shear

PARTICLES =   particles_dust

REAL_PRECISION=double
CFLAGS_GENERAL=-DDOUBLE_PRECISION
