###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM=mpicomm
FORCING=forcing
ENTROPY=noentropy
MAGNETIC=nomagnetic
HYDRO=hydro
DENSITY=density
TESTFIELD=test_methods/testfield_xz
SHEAR=shear
VISCOSITY=viscosity
