###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM   =   mpicomm

HYDRO     =   hydro
DENSITY   =   density
ENTROPY   = noentropy
MAGNETIC  =   magnetic
RADIATION = noradiation
PSCALAR   = nopscalar

GRAVITY   =   gravity_r
FORCING   = noforcing
SHEAR     = noshear
SHOCK     =   shock

SPECIAL = special/rtime_phiavg

