###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM     =   mpicomm
REAL_PRECISION = double
HYDRO       =   hydro
GRAVITY     = nogravity
DENSITY     =   density
ENTROPY     = noentropy
MAGNETIC    = nomagnetic
FORCING     = noforcing
SHOCK       =   shock
SELFGRAVITY =   selfgravity
POISSON     =   poisson
VISCOSITY   =   viscosity

INITIAL_CONDITION  =   initial_condition/bonnor_ebert_sphere
#INITIAL_CONDITION  =   initial_condition/alfven_wave

FOURIER     =   fourier_fftpack
POWER       =   power_spectrum
