###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

LIBSIG=-L$(HOME)/f90/lib
LDMPI=-lmpi
MPICOMM   = nompicomm
IO        =   io_dist

HYDRO     =   hydro
DENSITY   =   density
ENTROPY   =   entropy
MAGNETIC  = nomagnetic
RADIATION = noradiation
PSCALAR   = nopscalar

GRAVITY   = nogravity
FORCING   = noforcing
SHEAR     = noshear
