<ul>
	<li><a href="/samples/1d-tests/sod_10-1000.php">Sod shock tube tests</a></li>
	<li><a href="/samples/2d-tests/conv-slab-2d.php">2-D convection slab</a></li>
	<li><a href="/samples/turbulence/helical-MHDturb32-4procs/">helical MHD turbulence</a></li>
	<li><a href="/samples/turbulence/hydro512f/">non-helical hydro turbulence</a></li>
	<li><a href="/samples/shearing-box/">Shearing box</a></li>
        <li><a href="/samples/2d-tests/Rayleigh-Taylor/">Rayleigh-Taylor instability</a> [is this ^/samples/2d-tests/Rayleigh-Taylor/ ?]</li>
        <li><a href="/samples/2d-tests/Kelvin-Helmholtz/">Kelvin-Helmholtz</a> [is this ^/samples/2d-tests/Kelvin-Helmholtz/ ?]</li>
</ul>

