###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM  =   mpicomm
EOS      = noeos
HYDRO    = nohydro
DENSITY  = nodensity
ENTROPY  = noentropy
VISCOSITY= noviscosity
MAGNETIC = nomagnetic
GRAVITY  = nogravity
FORCING  = noforcing
FOURIER  =   fourier_fftpack
POWER    =   power_spectrum
SPECIAL  =   special/gravitational_waves_hTXk
REAL_PRECISION=double
