###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###
MPICOMM   = nompicomm

HYDRO     =   hydro
DENSITY   =   density
ENTROPY   =   temperature_idealgas
MAGNETIC  =   magnetic
RADIATION = noradiation

GRAVITY   =   gravity_simple
FORCING   = noforcing
SHEAR     = noshear
SHOCK	  =   shock

FOURIER   =   fourier_fftpack
