###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###
MPICOMM   =   mpicomm

HYDRO     =   hydro
DENSITY   =   density
ENTROPY   =   temperature_idealgas
MAGNETIC  =   magnetic
RADIATION = noradiation

GRAVITY   =   gravity_simple
FORCING   = noforcing
SHEAR     = noshear
SHOCK	  =   shock

SPECIAL   =   special/solar_corona

FOURIER   =   fourier_fftpack

REAL_PRECISION = double
