###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM      = nompicomm

HYDRO        = nohydro
DENSITY      = nodensity
ENTROPY      = noentropy
MAGNETIC     = nomagnetic
RADIATION    = noradiation
PSCALAR      = nopscalar

GRAVITY      = nogravity
SELFGRAVITY  =   selfgravity
POISSON      =   poisson
FORCING      = noforcing
SHEAR        =   shear
VISCOSITY    = noviscosity

DUSTDENSITY  = nodustdensity
DUSTVELOCITY = nodustvelocity

PARTICLES             =   particles_dust
PARTICLES_SELFGRAVITY =   particles_selfgravity

FOURIER      =   fourier_fftpack


# Use double precision
REAL_PRECISION = double

