#!/bin/bash
#SBATCH -N 2
#SBATCH -p gpu
#SBATCH -t 00:05:00
#SBATCH --gres=gpu:2
#SBATCH --constraint=k40

#module load gcc/4.9.3 cuda/7.5 openmpi/2.0.1

rm -f LOCK
start.csh
touch data/jobid.dat
run.csh
