#!/bin/bash -l
#SBATCH -N 2
#SBATCH -n 2
#SBATCH -p gpu
#SBATCH -t 00:05:00
#SBATCH --gres=gpu:k80:1
#SBATCH --ntasks-per-node=1

module load gcc/6.2.0 cmake/3.5.2 openmpi/2.1.2 cuda/9.0 
#srun --cpus-per-task=1 -N 1 -n 1 --ntasks-per-node=1 --gres=gpu:k80:1 ./run.csh

rm -f LOCK
./start.csh
touch data/jobid.dat
./run.csh
