#!/bin/bash

sed -f scripts/cparam.sed cparam.local > cparam.local_c.h

echo '#define MIN(a,b) (a<b ? a : b)' > cparam_c.h
echo '#define MAX(a,b) (a>b ? a : b)' >> cparam_c.h

sed -f scripts/cparam.sed cparam.f90 >> cparam_c.h
# the following needs to stay here in this order!
echo '#pragma once' > cparam_pencils.inc_c.h
sed -f scripts/cparam.sed cparam_pencils.inc >> cparam_pencils.inc_c.h
echo '#pragma once' > cparam.inc_c.h
sed -f scripts/cparam.sed cparam.inc >> cparam.inc_c.h
