#!/bin/sh

dollar='$'
script='

    s/\bSELFGRAVITY\b/\$(SELFGRAVITY).o/i;
    s/\bMESSAGES\b/messages.o/i;
    s/\bMPICOMM\b/\$(MPICOMM_FIX).o/i;
    s/\bGLOBAL\b/\$(GLOBAL).o/i;
    s/\bIO\b/\$(IO).o/i;
    s/\bPOWER_SPECTRUM\b/\$(POWER).o/i;
    s/\bPLANET\b/\$(PLANET).o/i;
    s/\bPARTICLES\b/\$(PARTICLES).o/i;
    s/\bPARTICLES_SUB\b/\$(PARTICLES_SUB).o/i;
    s/\bPARTICLES_MAIN\b/\$(PARTICLES_MAIN).o/i;
    s/\bPARTICLES_RADIUS\b/\$(PARTICLES_RADIUS).o/i;
    s/\bPARTICLES_NUMBER\b/\$(PARTICLES_NUMBER).o/i;
    s/\bPARTICLES_SELFGRAVITY\b/\$(PARTICLES_SELFGRAVITY).o/i;
    s/\bHYDRO\b/\$(HYDRO).o/i;
    s/\bVISCOSITY\b/\$(VISCOSITY).o/i;
    s/\bDENSITY\b/\$(DENSITY).o/i;
    s/\bENTROPY\b/\$(ENTROPY).o/i;
    s/\bMAGNETIC\b/\$(MAGNETIC).o/i;
    s/\bRADIATION\b/\$(RADIATION).o/i;
    s/\bPSCALAR\b/\$(PSCALAR).o/i;
    s/\bDUSTVELOCITY\b/\$(DUSTVELOCITY).o/i;
    s/\bDUSTDENSITY\b/\$(DUSTDENSITY).o/i;
    s/\bINTERSTELLAR\b/\$(INTERSTELLAR).o/i;
    s/\bCOSMICRAY\b/\$(COSMICRAY).o/i;
    s/\bCOSMICRAYFLUX\b/\$(COSMICRAYFLUX).o/i;
    s/\bSTRUCT_FUNC\b/\$(STRUCT_FUNC).o/i;
    s/\bINITCOND_SPEC\b/\$(INITCOND_SPEC).o/i;
    s/\bGRAVITY\b/\$(GRAVITY).o/i;
    s/\bEQUATIONOFSTATE\b/\$(EOS).o/i;
    s/\bFORCING\b/\$(FORCING).o/i;
    s/\bSHEAR\b/\$(SHEAR).o/i;
    s/\bTIMEAVG\b/\$(TIMEAVG).o/i;
    s/\bSPECIAL\b/\$(SPECIAL).o/i;
    s/\bTESTFIELD\b/\$(TESTFIELD).o/i;
    s/\bSHOCK\b/\$(SHOCK).o/i;
    s/\bCHIRAL\b/\$(CHIRAL).o/i;
    s/\bGRID\b/\$(GRID).o/i;

    s/\bPARTICLES_CDATA\b/\particles_cdata.o/i;
    s/\bCDATA\b/cdata.o/i; 
    s/\bPERSIST\b/persist.o/i; 
    s/\bCPARAM\b/cparam.o/i; 
    s/\bBOUNDCOND\b/boundcond.o/i;
    s/\bFILTER\b/filter.o/i;
    s/\bINITCOND\b/initcond.o/i;
    s/\bTIMESTEP\b/timestep.o/i;
    s/\bWSNAPS\b/wsnaps.o/i;
    s/\bSUB\b/sub.o/i;
    s/\bEQU\b/equ.o/i;
    s/\bPRINT\b/prints.o/i;
    s/\bREGISTER\b/register.o/i;
    s/\bPARAM_IO\b/param_io.o/i;
    s/\bDERIV\b/deriv.o/i;
    s/\bSLICES\b/slices.o/i;
    s/\bBORDERPROFILES\b/border_profiles.o/i;
    s/\bGENERAL\b/general.o/i;
    s/\bPRINT\b/prints.o/i;
    s/\bSNAPSHOT\b/snapshot.o/i;
'

while [ "$1" ]
do
  file="$1"
  if [ -e "$file" ]; then
    if [ "${file%.c}" != "$file" ]; then
      echo "${file%.c}.o: $file" 
    else
      used=`perl -ne 'print "$1\n" if m/^\s*use\s*([\w\d]*)/ ' $file | tr '[:lower:]' '[:upper:]' | sort | uniq `
      depends=`echo $used | perl -npe "$script"`
      includes=`perl -ne "print \"${dollar}1 \" if m/^\s*include\s*\\'([\S]*\\.(inc|local))\\'/ ;" $file `

      echo "${file%.f90}.o: $file $includes $depends" 
    fi
  fi
  shift
done
