###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

LIBSIG=-L$(HOME)/f90/lib
LDMPI=-lmpi
MPICOMM=nompicomm
GRAVITY=nogravity
FORCING=noforcing
ENTROPY=entropy
MAGNETIC=nomagnetic
SHOCK=shock
HYDRO=hydro
DENSITY=density
IO=io_dist

