### $Id$
### Machine Specific Makefile for modular pencil code
### 
### The appropriate Makefile will be chosen from the config tree and included during at compile time 
### 

## Uncomment this line to inherit the Makefile in the parent directory
include ../Makefile

FFLAGS= -64 -O3 -mips4 -r12000 
FFLAGS= -64 -O3 -auto_use mpi_interface -mips4 
