###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

LDMPI    =-lmpi

MPICOMM  =   mpicomm
IO       =   io_dist

HYDRO    =   hydro
DENSITY  =   density
ENTROPY  = noentropy
MAGNETIC =   magnetic
EOS      =   eos_idealgas
RADIATION=   radiation_ray

GRAVITY  = nogravity
FORCING  = noforcing

INITIAL_CONDITION = initial_condition/fluxrings
