#!/bin/csh
./start.csh
#cd src
#sed -e 's/REAL/DOUBLE_PRECISION/g' -e 's/MPI_COMPLEX/MPI_DOUBLE_COMPLEX/g' mpicomm.f90 > mpicomm_double.f90
#make mpicomm_double.o
#make hydro_kinematic.o
#make linkonly
#cd ..
./run.csh '-np 4' ' SDB_tine_test/a.out ' ' >ee.txt'
