###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM  = nompicomm

HYDRO    =   hydro
ENTROPY  =   temperature_idealgas
DENSITY  =   experimental/boussinesq
FOURIER  =   fourier_fftpack
POISSON  =   poisson
