###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM=mpicomm
FORCING=forcing
#ENTROPY=noentropy
MAGNETIC=magnetic
HYDRO=hydro
DENSITY=density
IO=io_dist
