###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

LIBSIG=-L$(HOME)/f90/lib
LDMPI=-lmpi
MPICOMM=mpicomm
GRAVITY=nogravity
FORCING=forcing
ENTROPY=noentropy
MAGNETIC=magnetic
HYDRO=hydro
DENSITY=density
IO=io_dist
TRANSFORM=transform_mpi
