###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM=nompicomm
GRAVITY=nogravity
ENTROPY=entropy
MAGNETIC=nomagnetic
HYDRO=hydro
DENSITY=density
EOS=eos_fixed_ionization
