###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM=mpicomm
GRAVITY=nogravity
FORCING=forcing
ENTROPY=noentropy
MAGNETIC=magnetic
HYDRO=hydro
EOS=eos_idealgas
DENSITY=density
PSCALAR=pscalar_nolog
POISSON=poisson
SPECIAL=special/advective_gauge
FOURIER=fourier_fftpack
POWER=power_spectrum
