###  -*-Makefile-*-  (for Emacs)    vim:set filetype=make:  (for vim)
###
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM   =   mpicomm
GLOBAL    = noglobal
VISCOSITY = noviscosity

HYDRO     = nohydro
DENSITY   = nodensity
ENTROPY   =   temperature_ionization
MAGNETIC  = nomagnetic
RADIATION = noradiation
PSCALAR   = nopscalar
EOS       = eos_chemistry
CHEMISTRY = chemistry

GRAVITY   = nogravity
FORCING   = noforcing
SHEAR     = noshear

SPECIAL   = special/alphadisk special/photoelectric_dust

REAL_PRECISION = double
