###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM   = nompicomm
HYDRO     =   hydro
DENSITY   =   density
ENTROPY   =   temperature_ionization
CHEMISTRY =   chemistry
EOS       =   eos_chemistry
REAL_PRECISION=double
NSCBC = NSCBC
SPECIAL = special/jet
