#
# BAOBAB cluster (Switzerland). Used by Antonino Midiri, Touko Puro.
#
%include compilers/GNU-GCC_MPI

%section Makefile
	FFLAGS += -llibrary -march=native -g  -ffree-line-length-none -fPIC
	FFLAGS += -mcmodel=large
	CFLAGS += -O2 -fPIC
	LDFLAGS += -ldl -Wl,--no-relax
        CUDA_AWARE_MPI=OFF
%endsection Makefile

%section runtime
	mpiexec = srun
%endsection runtime

