###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM   =   mpicomm
IO        =   io_hdf5
HYDRO     =   hydro
DENSITY   =   density
ENTROPY   =   entropy
EOS       = eos_idealgas
GRAVITY   =   gravity_simple
SPECIAL   =   special/dampuu
REAL_PRECISION = double
