###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

LDMPI=-lmpi
MPICOMM=nompicomm
GRAVITY=nogravity
FORCING=noforcing
ENTROPY=entropy
MAGNETIC=nomagnetic
HYDRO=hydro
DENSITY=density
IO=io_dist
POWER=nopower_spectrum
#EOS=eos_ionization
EOS=eos_idealgas

REAL_PRECISION=double
