###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM   =   mpicomm
IO        =   io_collect
FILE_IO   =   file_io_f95
DIAGNOSTICS =   diagnostics_runtime

HYDRO     =   hydro
DENSITY   =   density
ENTROPY   =   entropy
MAGNETIC  = nomagnetic
RADIATION = noradiation
PSCALAR   = nopscalar

EOS       = eos_idealgas
GRAVITY   =   gravity_simple
FORCING   = noforcing
SHEAR     = noshear
