#!/bin/bash -l
#SBATCH -N 1
#SBATCH -n 12
#SBATCH -J python-mpi
#SBATCH -p parallel
#SBATCH -t 10:00:00
##SBATCH -p test
##SBATCH -t 00:30:00
#SBATCH --mem-per-cpu=8000
#SBATCH --cpus-per-task=2
#SBATCH -o python-mpi%J.out
#SBATCH -e python-mpi%J.err

module purge
module load python-env/3.5.3
module load hdf5-par
export PYTHONPATH=$USERAPPL/Pencilcodepython3/lib/python3.5/site-packages
export PYTHONPATH="$PYTHONPATH:$PENCIL_HOME/python"
module list

srun python par-fort2h5.py
