###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM=mpicomm
GRAVITY=nogravity
FORCING=noforcing
ENTROPY=noentropy
MAGNETIC=nomagnetic
VISCOSITY=noviscosity
HYDRO=nohydro
EOS=noeos
DENSITY=nodensity
SPECIAL = special/backreact_infl
REAL_PRECISION=double
