#!/bin/bash
#SBATCH -A TG-AST140014   # project account name
#SBATCH -J elias227         # job name
#SBATCH -o elias227.o%j     # output and error file name (%j expands to jobID)
#SBATCH -e elias227.e%j     # output and error file name (%j expands to jobID)
#SBATCH -N 1               # Total # of nodes
#SBATCH -n 32              # Total # of mpi tasks
#SBATCH -p normal    # queue (partition) -- normal, development, etc.
#SBATCH -t 20:00:00       # run time (hh:mm:ss) - 1.5 hours
##SBATCH -d=arfterok:     # depend
#
rm -f LOCK
touch NEVERLOCK
./start.csh
./run.csh
