###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM           =   mpicomm
GLOBAL            = noglobal

HYDRO             =   hydro
DENSITY           =   density
ENTROPY           =   entropy
MAGNETIC          = nomagnetic
RADIATION         = noradiation
PSCALAR           = nopscalar

GRAVITY           = nogravity
FORCING           = noforcing
SHEAR             = noshear

FOURIER           = fourier_fftpack
SHOCK             =   shock_highorder

BORDER_PROFILES   =   border_profiles

POINTMASSES       =   pointmasses

INITIAL_CONDITION =   initial_condition/centrifugal_balance

REAL_PRECISION    =   double

