#
# Roihu (Nvidia GH200 Grace Hopper, CSC Kajaani, Finland)
#
%include compilers/GNU-GCC_MPI
#%include compilers/extensions/GNU-GCC_debug

%section Makefile

	# turn on hardware optimizations
	FFLAGS += -g -llibrary -march=native # -fPIC
	#Roihu is really vulnerable to these
        #FFLAGS += -Warray-temporaries
	#Not implemented on the default Fortran compiler of Roihu
	FFLAGS += -mcmodel=large
	CFLAGS += -O2 -fPIC
	LDFLAGS += -ldl -Wl,--no-relax
%endsection Makefile

%section runtime
	mpiexec = srun
        ##use pc_auto-test --exec-opts="--account=<your project> -p test"
	#mpiexec_opts += --account=project_2001062
%endsection runtime

