###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM=nompicomm
ENTROPY=entropy
MAGNETIC=nomagnetic
HYDRO=hydro
DENSITY=density
SHOCK=shock_highorder
