###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM  = nompicomm
GRAVITY  = nogravity
FORCING  = noforcing
ENTROPY  =   thermal_energy
MAGNETIC = nomagnetic
HYDRO    =   hydro
DENSITY  =   density
SHOCK    =   shock_highorder
POWER    = nopower_spectrum

WENO_TRANSPORT = weno_transport
