###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM=mpicomm
GRAVITY=nogravity
FORCING=noforcing
ENTROPY=noentropy
MAGNETIC=magnetic
VISCOSITY=noviscosity
HYDRO=nohydro
EOS=noeos
DENSITY=nodensity
FOURIER=fourier_fftpack
POWER=power_spectrum
SPECIAL = special/backreact_infl special/disp_current
REAL_PRECISION=double
