default:
	latex notes
	bibtex notes
	latex notes
	latex notes
	dvipdf notes

2023:
	latex 2023
	bibtex 2023
	latex 2023
	latex 2023
	dvipdf 2023

2022:
	latex 2022
	bibtex 2022
	latex 2022
	latex 2022
	dvipdf 2022

clean:
	rm -f *.log *.dvi *.bbl *.blg *.aux
