###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

LDMPI=-lmpi
MPICOMM=nompicomm
GRAVITY=nogravity
FORCING=forcing
ENTROPY=noentropy
MAGNETIC=magnetic
HYDRO=hydro
DENSITY=density
IO=io_dist
FOURIER=fourier_fftpack
POWER=power_spectrum
