### $Id$
### Machine Specific Makefile for modular pencil code
### 
### The appropriate Makefile will be chosen from the config tree and included during at compile time 
### 

## Uncomment this line to inherit the Makefile in the parent directory
include ../Makefile

FC=pgf90 
FFLAGS= -fast -lm -Nscampi   
F90FLAGS= 
F77=$(FC) -lm  
