 iuu=           1
 ilnrho=           4
 iss=           5
 nname=          11
 iuu=           1
 iux=           1
 iuy=           2
 iuz=           3
 nname=          11
 ilnrho=           4
 irho=           0
 nname=          11
 iss=           5
 iyH=           0
 ilnTT=           0
 nname=          11
 nnamexy=          -1
 nnamez=          -1
 iaa=           0
 iax=           0
 iay=           0
 iaz=           0
 nname=          11
 ifx=           0
 ify=           0
 ifz=           0
 iQrad=           0
 ikapparho=           0
 iSrad=           0
 ikappa=           0
 ilnTT=           0
 iKR_Frad=           0
 iKR_Fradx=           0
 iKR_Frady=           0
 iKR_Fradz=           0
 ilncc=0
 icc=0
 iXX_chiral=0
 iYY_chiral=0
 ind=           0
 nname=          11
 iuun=           0
 iunx=           0
 iuny=           0
 iunz=           0
 nname=          11
 ilnrhon=           0
 iecr=           0
 igg=           0
 igx=           0
 igy=           0
 igz=           0
 ipotself=0
 ihypvis=           0
