 <div id="rightcolumn">
                <div class="rightcolumnpad">
                        <h2>Latest News</h2>
                        <p>Pencil Code User Meeting 2013 on 17-20 June in Lund. <a href="news.html">Read More...</a></p>
                        </div>
                        <div class="rightdivider"></div>
                        <div class="rightcolumnpad">
                        <h2>Download</h2>
                        <p> Here you can download the code. <a href="download.html">Download</a></p>
                        </div>
                        <div class="rightdivider"></div>
                        <div class="rightcolumnpad">
                        <h2>Documentation</h2>
                        <p> 
                        <!--Quick links:
                        
                        <small>
                        <ul>
                        		<li>	<a href="doc/manual.pdf">Full manual.</a> </li>
                           <li> <a href="doc/quick-guide/quick_start.pdf">Quick-guide for beginners.</a> </li>
                            </ul>
                          </small>  -->
                          Manual, quick start guide for beginners, samples and 
                        <a href="documentation.html">more...</a></p>
                </div>
        </div>
