<div class="rightcolumn">

<h2>Pencil News</h2>
The next Pencil Code User Meeting will be in summer 2014. <a href="/news.php">[more...]</a>

<div class="rightdivider"></div>

<h2>Get Pencil</h2>
There are several ways how to get the code. <a href="/download.php">[more...]</a>

<div class="rightdivider"></div>

<h2>Learn Pencil</h2>
Quick start guide for beginners, samples, manual &amp; <a href="/doc.php">[more...]</a>

</div><!-- End of rightcolumn -->

