<div class="rightcolumn">

<h2>Latest News</h2>
The next Pencil Code User Meeting will be in summer 2014. <a href="/news.php">[more...]</a>

<div class="rightdivider"></div>

<h2>Download</h2>
There are several ways how to get the code. <a href="/download.php">[more...]</a>

<div class="rightdivider"></div>

<h2>Learn Pencil</h2>
Manual, quick start guide for beginners, samples and <a href="/doc.php">[more...]</a>

</div><!-- End of rightcolumn -->

