#!/bin/csh

# Name:   epstopdf_all
# Author: wd (Wolfgang.Dobler@ncl.ac.uk)
# Date:   29-Aug-2002
# Description:
#   Run epstopdf, and produce a .bb file for all input files

foreach f ($*)
  set base = $f:r
  epstopdf $f
  grep '^%%BoundingBox' $f > $base.bb
end

# End of file epstopdf_all
