// Generated by Pencil Code build, yet meant to be edited by the user.
// All needed rhs functions are provided, but unneeded ones are not removed.


#if LHYDRO
duu_dt(int step_num){
    suppress_unused_warning(step_num)
    #include "../hydro/momentum.h"
}
#endif

#if LDENSITY
dlnrho_dt(int step_num){
    suppress_unused_warning(step_num)
    #include "../density/continuity.h"
}
#endif

#if LMAGNETIC
daa_dt(int step_num){
    suppress_unused_warning(step_num)
    #include "../magnetic/induction.h"
}
#endif

#if LENERGY
denergy_dt(int step_num){
    suppress_unused_warning(step_num)
    #include "../entropy/heat_ss.h"
}
#endif

