###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM   = nompicomm

HYDRO     = nohydro
DENSITY   =   density
ENTROPY   = noentropy
MAGNETIC  = nomagnetic
RADIATION = noradiation
PSCALAR   =   pscalar

GRAVITY   = nogravity
FORCING   = noforcing
SHEAR     = noshear
VISCOSITY = noviscosity

DUSTDENSITY  = nodustdensity
DUSTVELOCITY = nodustvelocity

PARTICLES        =   particles_dust
PARTICLES_RADIUS =   particles_radius
PARTICLES_NUMBER =   particles_number


# Use double precision
REAL_PRECISION = double
