###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

LIBSIG   =-L$(HOME)/f90/lib
LDMPI    =-lmpi

MPICOMM  = nompicomm
IO       =   io_dist

HYDRO    =   hydro
DENSITY  =   density
ENTROPY  = noentropy
MAGNETIC =   magnetic

GRAVITY  = nogravity
FORCING  = noforcing

