###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM   =   nompicomm
GLOBAL    =   global_avgs

HYDRO     =   hydro
DENSITY   =   density
ENTROPY   = noentropy
MAGNETIC  = nomagnetic
RADIATION = noradiation
PSCALAR   = nopscalar

GRAVITY   =   grav_r
FORCING   = noforcing
SHEAR     = noshear
SHOCK     =   shock
PLANET    =   planet

PARTICLES = particles_planet

# Compile using double precision
#FFLAGS_GENERAL=-r8
#CFLAGS_GENERAL=-DDOUBLE_PRECISION
REAL_PRECISION=double

