###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM      = nompicomm
GLOBAL       =   global_gg_cs2_nolnrho

HYDRO        =   hydro
DENSITY      =   density
ENTROPY      = noentropy
MAGNETIC     = nomagnetic
RADIATION    = noradiation
PSCALAR      = nopscalar
VISCOSITY    =   viscosity

GRAVITY      =   grav_r
FORCING      = noforcing
SHEAR        = noshear
SHOCK        =   shock
PLANET       =   planet

#DUSTDENSITY  =   dustdensity
#DUSTVELOCITY =   dustvelocity

PARTICLES    =   particles_planet

#NESTING   =   nest
