###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM   =   nompicomm
GLOBAL    =   global_avgs

HYDRO     =   hydro
DENSITY   =   density
ENTROPY   = noentropy
MAGNETIC  = nomagnetic
RADIATION = noradiation
PSCALAR   = nopscalar

GRAVITY   = nogravity
FORCING   = noforcing
SHEAR     = noshear
SHOCK     =   shock

PARTICLES       = particles_dust
PARTICLES_NBODY = particles_nbody
BORDER_PROF     = border_profiles
PLANET    = planet

#REAL_PRECISION=double

