###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM   = nompicomm

HYDRO     =   hydro
DENSITY   =   density
ENTROPY   =   temperature_idealgas
MAGNETIC  = nomagnetic
GRAVITY   =   gravity_simple
IMPLICIT_PHYSICS = implicit_physics

REAL_PRECISION = double
