###  -*-Makefile-*-  (for Emacs)    vim:set filetype=make:  (for vim)
###
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM   =   mpicomm

HYDRO     =   hydro
DENSITY   =   density
ENTROPY   =   entropy
MAGNETIC  =   magnetic
DERIV     =   deriv_10th
REAL_PRECISION=double

#REAL_PRECISION = double
