###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM =   mpicomm
#IO      =   io_mpi2

HYDRO   =   hydro
DENSITY =   density
SHEAR   =   shear

PARTICLES      =   particles_dust
PARTICLES_DRAG =   particles_drag

REAL_PRECISION = double
