###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

LDMPI=-lmpi

MPICOMM   =   mpicomm
IO        =   io_dist

HYDRO     =   hydro
DENSITY   =   density
ENTROPY   = noentropy
MAGNETIC  = nomagnetic
RADIATION = noradiation
PSCALAR   = nopscalar
EOS       =   eos_idealgas

GRAVITY   = nogravity
FORCING   = noforcing
SHEAR     = noshear
TIMEAVG   = notimeavg
