###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM   = nompicomm
HYDRO     =   hydro
DENSITY   =   density
ENTROPY   =   entropy
MAGNETIC  =   magnetic
EOS       =   eos_idealgas
GRAVITY   =   gravity_simple
SHEAR     =   shear
TESTFIELD = notestfield
