###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM   = nompicomm

HYDRO     =   hydro
DENSITY   =   density
ENTROPY   = noentropy
MAGNETIC  =   magnetic
RADIATION = noradiation
PSCALAR   = nopscalar

GRAVITY   = nogravity
FORCING   = noforcing
SHEAR     =   shear

HYPERVISC_STRICT =   hypervisc_strict_2nd
HYPERRESI_STRICT =   hyperresi_strict_2nd

FOURIER   =   fourier_fftpack

REAL_PRECISION = double
