###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM   = nompicomm

HYDRO     =   hydro
DENSITY   =   density
ENTROPY   = noentropy
MAGNETIC  = nomagnetic

GRAVITY   =   gravity_r
SHEAR     = noshear

INITIAL_CONDITION = initial_condition/viscous_ring
SPECIAL = special/set_gravity
