### $Id: Makefile,v 1.1 2003-08-25 13:05:18 mee Exp $
### Machine Specific Makefile for modular pencil code
### 
### The appropriate Makefile will be chosen from the config tree and included during at compile time 
### 

## Uncomment this line to inherit the Makefile in the parent directory
include ../Makefile

FC=ifc 
F77=$(FC) -dusty 
