###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM      =   mpicomm
HYDRO        =   hydro
DENSITY      =   density
ENTROPY      =   entropy
MAGNETIC     = nomagnetic

GRAVITY      = nogravity
SHEAR        = noshear

SHOCK        =   shock_highorder

INITIAL_CONDITION = initial_condition/kelvin_helmholtz

REAL_PRECISION = double



