###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM  =   mpicomm
GRAVITY  = nogravity
FORCING  = noforcing
ENTROPY  = noentropy
MAGNETIC = nomagnetic
HYDRO    =   hydro
DENSITY  =   density
SHOCK    = noshock
POWER    = nopower_spectrum
#REAL_PRECISION=double
