###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM=nompicomm
MPICOMM=mpicomm
HYDRO=hydro
DENSITY=density
MAGNETIC=magnetic
FOURIER=fourier_fftpack
