###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

LDMPI=
MPICOMM=nompicomm
GRAVITY=nogravity
FORCING=forcing
ENTROPY=noentropy
MAGNETIC=magnetic
HYDRO=hydro
EOS=eos_idealgas
DENSITY=density
PSCALAR=pscalar_nolog
IO=io_dist
FOURIER=fourier_fftpack
POWER=power_spectrum
