###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

LIBSIG=-L$(HOME)/f90/lib
LDMPI=
MPICOMM=nompicomm
GLOBAL=global_rr
GRAVITY=nograv
FORCING=forcing
ENTROPY=noentropy
MAGNETIC=magnetic
DENSITY=density
HYDRO=hydro
IO=io_dist

#AB: I would use this to overwrite some default.
#AB: Can one not touch this file to make sure it always exists?

