### $Id$
### Machine Specific Makefile for modular pencil code
### 
### The appropriate Makefile will be chosen from the config tree and included during at compile time 
### 

## Uncomment this line to inherit the Makefile in the parent directory
include ../Makefile


CFLAGS=-O3 -DFUNDERSC=0





F77=mpxlf
FC=mpxlf90

FLAGS=-O5 -qstrict
F90FLAGS=-qsuffix=f=f90
LDMPI=

