#!/bin/sh
#  -*-Perl-*-
#======================================================================#
# Run the right perl version:
if [ -x /usr/local/bin/perl ]; then
  perl=/usr/local/bin/perl
elif [ -x /usr/bin/perl ]; then
  perl=/usr/bin/perl
else
  perl=`which perl| sed 's/.*aliased to *//'`
fi

exec $perl -x -S $0 "$@";     # -x: start from the following line
#======================================================================#
#! /Good_Path/perl -w 
# line 17

# Name:   
# Author: 
# Date:   14-Aug-2003
# CVS: $Id$
# Description:
#
#   DESCRIPTION
#
#
#   THE_DATE/PERSON: 
#
# ---------------------------------------------------------------------- #
my %systems  = ( # os { machine, machine, ... }, ... 
	          'IRIX64'   => { 
		                'embla'=>'',
		                'gridur'=>'',
		                'balder'=>'',
		                'sander'=>'',
		                'antares'=>'',
		                'Grand'=>'',
		                'ukaff'=>'',
		                'origin'=>'',
		                'wrenstandard'=>'',
		                'wrencache'=>'',
		                'wrenpacx'=>'',
		                'wren'=>'',
		                'tacsg2'=>''
                              },
	          'OSF1'     => { 
		                'mhd0'=>''
                              },
	          'Linux'    => {
		                'fire'=>'',
		                'copson'=>'',
		                'Samos'=>'',
		                'Cincinnatus'=>'',
		                'Owen'=>'',
		                'Master'=>'',
		                'ns0'=>'',
		                'fe0'=>'',
		                'nl6'=>'',
		                'mmtf'=>'',
		                'nl19'=>'',
		                'hamlet'=>'',
		                'nw46'=>'',
		                'karbala'=>'',
		                'erland'=>'',
		                'igor'=>'',
		                'tycho'=>'',
		                'linux29'=>'',
		                'onsager'=>'',
		                'fe4'=>'',
		                'fe9'=>'',
		                'monolith'=>'',
		                'nw50'=>'',
		                'Mephisto'=>'',
		                'nl3'=>'',
		                'cosmo'=>'',
		                'nw17'=>'',
		                'nl11'=>'',
		                'wormhole'=>'',
		                'sandin'=>'',
		                'nl3'=>'',
		                'morvern'=>''
                              },
	          'SunOS'    => {
		                'Lomond'=>'',
				'ursa'=>''
                              },
                  'UNICOS/mk' => {},
		  'HI-UX/MPP' => {},
		  'SUPER-UX'  => {},
		  'AIX'       => {}
		  
	      );
# ---------------------------------------------------------------------- #

while (my ($OS) = each %systems) {
    my $OS_lc=lc($OS);
    #print $OS;
    system("mkdir -p $OS");
    system("adapt-and-clean -o=$OS Makefile.treesource $OS.default");
    while (my ($host) = each %{$systems{$OS}}) {
        my $host_lc=lc($host);
	system("mkdir -p $OS");
        system("adapt-and-clean -o=$OS -h=$host Makefile.treesource $OS/$host");
    }
}



