### $Id$
### Machine Specific Makefile for modular pencil code
### 
### The appropriate Makefile will be chosen from the config tree and included during at compile time 
### 

## Uncomment this line to inherit the Makefile in the parent directory
# include ../Makefile


## Compiler flags:
##   FFLAGS are used by both the F90 compiler $(FC) and $(F77);
##   F90FLAGS are only used by $(FC)
##   F77FLAGS are only used by $(F77)

#
# Specify which Fortran 90 compiler to use
#
#FC=f90   #Use system default

#
# Specify the Fortran 77 compiler to use
#
#F77=f77  

#
# Specify which C compiler to use
#
#CC=gcc   #Use system default
CFLAGS=-O3 -DFUNDERSC=1
#
#
#
FFLAGS=-O3
#
#
#
F90FLAGS=
#
#
#
F77FLAGS=
#
#
#
LIBSIG=
#
# Specify the necessary libraries and library search paths to include
# eg.   LDMPI=-L /opt/mpich/lib -lmpi
#
LDMPI=-lmpi
#
#
#
FFLAGS_GENERAL=


