# Intel: FORTRAN compiler

%section Makefile
	FC = ifort
	F77 = $(FC)
	FFLAGS = -implicitnone
	FFLAGS_DOUBLE = -r8
	OMPFFLAGS += -qopenmp
	PPFLAGS += -fpp
	LDFLAGS = -Bdynamic
	FSTD_95 = -std95
	FSTD_2003 = -std03
	FSTD_2008 = -std08
	FSTD_2018 = -std08
	#Not sure would it be be the one below?
	#For safety now taking the old standard
	#FSTD_2018 = -std18
	MODULE_PREFIX = 
	MODULE_INFIX  = _mp_
	MODULE_SUFFIX = _
%endsection Makefile

%section environment
	MODULE_PREFIX = 
	MODULE_INFIX  = _mp_
	MODULE_SUFFIX = _
%endsection environment

