%section Makefile
	LDFLAGS_HELPER += -cuda 
	FFLAGS += -cuda
%endsection Makefile

%section runtime
  mpiexec = mpiexec
  mpiexec_opts  = --bind-to none #--cpus-per-proc $OMP_NUM_THREADS
                                 # this doesn't work inside container, why not?
%endsection runtime
