###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

LIBSIG=-L$(HOME)/f90/lib
LDMPI=-lmpi

MPICOMM      = nompicomm

HYDRO        =   hydro
DENSITY      =   density
ENTROPY      = noentropy
MAGNETIC     = nomagnetic
RADIATION    = noradiation
PSCALAR      = nopscalar
IONIZATION   =   ionization_fixed

GRAVITY      = nogravity
FORCING      = noforcing
IO           =   io_dist
SHEAR        = noshear

DUSTDENSITY  =   dustdensity
DUSTVELOCITY =   dustvelocity

FFTPACK      = nofftpack
FFT          = nofft


# Use double precision
REAL_PRECISION = double

