###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###
MPICOMM      = nompicomm

HYDRO        =   hydro
DENSITY      =   density
ENTROPY      = noentropy
MAGNETIC     = nomagnetic
RADIATION    = noradiation
PSCALAR      = nopscalar

GRAVITY      = nogravity
FORCING      = noforcing
SHEAR        = noshear
VISCOSITY    = noviscosity

DUSTDENSITY  =   dustdensity
DUSTVELOCITY =   dustvelocity

REAL_PRECISION = double
