###
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###
MPICOMM   =   mpicomm
GLOBAL    = noglobal

DRIVER    =   driver

HYDRO     =   hydro
DENSITY   = nodensity
ENTROPY   = noentropy
EOS       = noeos
MAGNETIC  = nomagnetic
RADIATION = noradiation

GRAVITY   = nogravity
FORCING   = noforcing
SHOCK     = noshock
SHEAR     = noshear

FOURIER   =   fourier_fftpack

REAL_PRECISION = double
