###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM   = nompicomm

HYDRO     = hydro
DENSITY   = density
MAGNETIC  = magnetic
EOS       = eos_idealgas
SHOCK     = shock_highorder
