###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

LIBSIG=-L$(HOME)/f90/lib
LDMPI=
MPICOMM = nompicomm
GRAVITY = nogravity
FORCING =   forcing
ENTROPY = noentropy
MAGNETIC=   magnetic
HYDRO   =   hydro
DENSITY =   density
IO      =   io_dist
EOS     =   eos_idealgas

