###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM  = nompicomm
GRAVITY  = nogravity
FORCING  = noforcing
ENTROPY  = noentropy
MAGNETIC = nomagnetic
HYDRO    =   hydro
DENSITY  =   density_anelastic
EOS      =   eos_idealgas
FOURIER  =   fourier_fftpack
POISSON  =   poisson
