### $Id$
### Machine Specific Makefile for modular pencil code
### 
### The appropriate Makefile will be chosen from the config tree and included during at compile time 
### 

## Uncomment this line to inherit the Makefile in the parent directory
include ../Makefile


FC=f90
FFLAGS= -64 -O3 -mips4
OPTFLAGS= -64
F77=$(FC)
CFLAGS=-O3 -64 -DFUNDERSC=1

