###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM   = nompicomm
IO        =   io_dist
TIMEAVG   = notimeavg

HYDRO     =   hydro
DENSITY   =   density
ENTROPY   =   entropy
MAGNETIC  =   magnetic
RADIATION = noradiation
PSCALAR   = nopscalar
EOS       =   eos_idealgas

GRAVITY   =   gravity_r
FORCING   = noforcing
SHEAR     = noshear
SHOCK     =   shock
