### $Id$
### Machine Specific Makefile for modular pencil code
### 
### The appropriate Makefile will be chosen from the config tree and included during at compile time 
### 

## Uncomment this line to inherit the Makefile in the parent directory
include ../Makefile


FC=f90
FFLAGS=-O4
CFLAGS=-O4 -DFUNDERSC=1
LDMPI=-L/opt/local/mpich/lib -lmpich -lsocket -lnsl -laio
F77=$(FC)

