###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM   =   mpicomm
IO        =   io_dist
FILE_IO   =   file_io_f2003

HYDRO     =   hydro
DENSITY   =   density
ENTROPY   =   entropy
MAGNETIC  =   magnetic
RADIATION = noradiation
PSCALAR   = nopscalar
EOS       =   eos_idealgas

GRAVITY   =   gravity_r
FORCING   = noforcing
SHEAR     = noshear
TIMEAVG   =   timeavg

REAL_PRECISION = double
