#!/usr/bin/perl
##
## $Id: pc_qjobname,v 1.4 2005-10-05 13:13:56 ajohan Exp $
##
$host = `hostname`;
#
# Go through list of hosts to use proper method.
#
if ($host =~ /fe[0-9]/){
  
  if ($#ARGV ne -1) { @jobs = @ARGV; }
  else {
    @jobs = `qstat | grep $ENV{'USER'} `;
    foreach $job (@jobs) { $job =~ s/([0-9]*\.[a-z]*) .*/$1/g; chomp $job; }
    }

  foreach $job (@jobs){
    $a = `qstat -f $job`;
    $a =~ s/\s//g;
    $a =~ /PBS_O_WORKDIR=(.*),PBS_O_SYSTEM/;
    $a = $1;
    $a =~ s/$ENV{'HOME'}/\~/g;
    print "$job : $a\n";
    }

  }
elsif ($host =~ /riologin/){   # SGE
  
  if ($#ARGV ne -1) { @jobs = @ARGV; }
  else {
    @jobs = `qstat | grep $ENV{'USER'} `;
    foreach $job (@jobs) { $job =~ s/^   ([0-9]*)/$1/g; $job=$1; chomp $job; }
    }

  foreach $job (@jobs){
    $a = `qstat -j $job | grep cwd:`;
    $a =~ /(\/.*)$/;
    $a = $1;
    $a =~ s/$ENV{'HOME'}/\~/g;
    print "$job : $a\n";
    }

  }
