// Generated by Pencil Code build, yet meant to be edited by the user.
// All needed rhs functions are provided, but unneeded ones are not removed.

#define LNRHO RHO

duu_dt(){
#include "../hydro/momentum.h"
}

dlnrho_dt(){
#include "../density/continuity.h"
}

daa_dt(){
#include "../magnetic/induction.h"
}

#include "../entropy/heat_cond_const_chi.h"

denergy_dt(){
#include "../entropy/heat_ss.h"
}


dlnrhon_dt(){return 0.}

duun_dt(){return real3(0.,0.,0.)}

dlncc_dt(){return 0.}

