###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM   = nompicomm
IO        =   io_dist

HYDRO     =   hydro
DENSITY   =   density
ENTROPY   =   temperature_ionization
MAGNETIC  = nomagnetic
RADIATION =   radiation_ray
EOS       =   eos_temperature_ionization
SHOCK     = noshock
PSCALAR   = nopscalar

GRAVITY   =   gravity_simple
FORCING   = noforcing
SHEAR     = noshear
POWER_SPECTRUM = nopower_spectrum
