###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM  =   mpicomm
GRAVITY  = nogravity
FORCING  = noforcing
ENTROPY  = noentropy
MAGNETIC = nomagnetic
HYDRO    =   hydro
DENSITY  =   density
SHOCK    = noshock
FOURIER  =   fourier_fftpack
POWER    =   power_spectrum
SPECIAL  =   special/gravitational_waves_hTXk
REAL_PRECISION=double

