###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM   = nompicomm
GLOBAL    = noglobal

HYDRO     = nohydro
DENSITY   = nodensity
ENTROPY   = noentropy
MAGNETIC  =   magnetic
RADIATION = noradiation
PSCALAR   = nopscalar

GRAVITY   = nogravity
FORCING   = noforcing
VISCOSITY = noviscosity
EOS       = noeos
SHEAR     = noshear
