###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM   = nompicomm
HYDRO     = experimental/hydro_kinematic
DENSITY   = nodensity
MAGNETIC  =   magnetic
VISCOSITY = noviscosity
EOS       = noeos
