###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

LDMPI=-lmpi

MPICOMM   =   mpicomm
IO        =   io_dist

HYDRO     =   hydro
DENSITY   =   density
ENTROPY   =   entropy
MAGNETIC  =   magnetic
RADIATION = noradiation
PSCALAR   = nopscalar

GRAVITY   =   gravity_r
FORCING   = noforcing
SHEAR     = noshear
TIMEAVG   = notimeavg
