###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM     =   mpicomm
HYDRO       =   hydro
DENSITY     =   density
ENTROPY     =   entropy
MAGNETIC    = nomagnetic
SHOCK       =   shock
VISCOSITY   =   viscosity
GRAVITY     =   gravity_r

SPECIAL = special/turbpotential

REAL_PRECISION = double

INITIAL_CONDITION = initial_condition/centrifugal_balance

BORDER_PROFILES = border_profiles
