###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM   = nompicomm
HYDRO     = nohydro
DENSITY   = nodensity
EOS       = noeos
ENTROPY   = noentropy
VISCOSITY = noviscosity
CHEMISTRY =   chemistry

