###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM   =   mpicomm
DENSITY   =   density
ENTROPY   =   entropy
VISCOSITY = noviscosity
EOS       = eos_idealgas
GRAVITY   =   gravity_simple
REAL_PRECISION = double
