###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

LIBSIG=-L$(HOME)/f90/lib
LDMPI=-lmpi

MPICOMM   = nompicomm
IO        =   io_dist

HYDRO     =   hydro
DENSITY   =   density
ENTROPY   =   entropy
MAGNETIC  =   magnetic
RADIATION = noradiation
PSCALAR   = nopscalar
EOS       =   eos_idealgas

GRAVITY   =   gravity_r
FORCING   = noforcing
SHEAR     = noshear
TIMEAVG   =   timeavg
