#!/bin/bash -l
##
## Example script for submitting python mpi job
## Depends on machine settings and processor/memory requirements
##
##SBATCH -N 1
#SBATCH -n 24
#SBATCH -J python-mpi	
#SBATCH -p parallel
#SBATCH -t 10:00:00
##SBATCH -p test
##SBATCH -t 00:30:00
#SBATCH --mem-per-cpu=4000
#SBATCH --cpus-per-task=2
#SBATCH -o python-mpi%J.out
#SBATCH -e python-mpi%J.err

module load gcc/5.4.0
module load intelmpi/5.1.3
module load hdf5-par/1.8.18
module load python-env/3.5.3
export PATH="$USERAPPL/appl_taito/myconda3/bin:$PATH"
export PYTHONPATH="$USERAPPL/myconda3/"
export PYTHONPATH="$PYTHONPATH:$PENCIL_HOME/python"
module list
source activate $USERAPPL/myconda3

mpirun python local_fort2h5.py
