default:
	pdflatex notes_2021
	pdflatex notes_2021
notes_2014:
	pdflatex notes_2014
	pdflatex notes_2014

old:
	pdflatex notes
	pdflatex notes

figs:
	epstopdf fig/pdardel_strong.eps
	epstopdf fig/ptriolith_strong.eps
	epstopdf fig/pcomp_performance_2014.eps

ln:
	ln -s ../figs/ fig

