###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM  = mpicomm
EOS      =   eos_idealgas
HYDRO    =   hydro
DENSITY  =   density
ENTROPY  = noentropy
MAGNETIC =   magnetic
GRAVITY  = nogravity
FORCING  =   forcing

FOURIER  =   fourier_fftpack
POWER    =   power_spectrum


#SIGNAL_HANDLING   =   signal_handling

TRAINING=training_torchfort
GPU=gpu_astaroth
TRANSPILATION=on
