###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM   =   nompicomm
HYDRO     =   hydro
DENSITY   =   density
MAGNETIC  =   magnetic
VISCOSITY =   viscosity
EOS       =   eos_idealgas
SPECIAL   =   special/chiral_mhd
REAL_PRECISION = double
FOURIER   =   fourier_fftpack
POWER     =   power_spectrum
