###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM  = nompicomm
GRAVITY  = gravity_simple
FORCING  = noforcing
ENTROPY  = noentropy
MAGNETIC = nomagnetic
HYDRO    =   hydro
DENSITY  =   special/anelastic
EOS      = eos_idealgas
FOURIER  =   fourier_fftpack
POISSON  =   poisson
