###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM=mpicomm
GRAVITY=nogravity
FORCING=noforcing
ENTROPY=noentropy
MAGNETIC=nomagnetic
VISCOSITY=noviscosity
HYDRO=nohydro
EOS=noeos
DENSITY=nodensity
FOURIER  =   fourier_fftpack
POWER    =   power_spectrum
SPECIAL = special/klein_gordon special/gravitational_waves_hTXk
REAL_PRECISION=double
