!$omp parallel copyin( &
!$omp dxyz_2  &
!$omp ,dxyz_4  &
!$omp ,dxyz_6  &
!$omp ,dvol  &
!$omp ,dxmax_pencil  &
!$omp ,dxmin_pencil  &
!$omp ,dline_1  &
!$omp ,lcoarse_mn  &
!$omp ,advec2_hypermesh  &
!$omp ,lfirstpoint  &
!$omp ,seed  &
!$omp ,m  &
!$omp ,n  &
!$omp ,itype_name  &
!$omp ,fname  &
!$omp ,fnamer  &
!$omp ,fname_sound  &
!$omp ,fnamex  &
!$omp ,fnamey  &
!$omp ,fnamez  &
!$omp ,fnamexy  &
!$omp ,fnamexz  &
!$omp ,fnamerz  &
!$omp ,ncountsz  &
!$omp ,fname_half  &
!$omp )
!$omp end parallel
