###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

LIBSIG=-L$(HOME)/f90/lib
LDMPI=-lmpi
MPICOMM=nompicomm
GLOBAL=global_rr
GRAVITY=nograv
FORCING=noforcing
ENTROPY=noentropy
MAGNETIC=nomagnetic
HYDRO=hydro
DENSITY=density
IO=io_dist

