###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM=mpicomm
GLOBAL=noglobal
GRAVITY=nogravity
#FORCING=forcing
ENTROPY=noentropy
MAGNETIC=magnetic
HYDRO=hydro
DENSITY=nodensity
IO=io_dist
#FOURIER=fourier_fftpack
#POWER=power_spectrum
SPECIAL=special/schur_triple_decomp
REAL_PRECISION=double
LIBRARIES = lapack blas
