###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM      = nompicomm

HYDRO        = nohydro
DENSITY      = nodensity
ENTROPY      = noentropy
MAGNETIC     = nomagnetic
RADIATION    = noradiation
PSCALAR      = nopscalar

GRAVITY      = nogravity
SELFGRAVITY  =   selfgravity
POISSON      =   poisson
FORCING      = noforcing
SHEAR        = noshear
VISCOSITY    = noviscosity
SPECIAL      =   special/Lambda_CDM

PARTICLES             =   particles_dust
PARTICLES_SELFGRAVITY =   particles_selfgravity

FOURIER      =   fourier_fftpack
POWER        = power_spectrum

# Use double precision
REAL_PRECISION = double

