name: Automatic pushpars
 on:

   schedule:
     - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: nvidia/cuda:12.9.0-devel-ubuntu24.04

    timeout-minutes: 180
    steps:
      - name: Set timezone
        run: ln -fs /usr/share/zoneinfo/Europe/Helsinki /etc/localtime

      - name: Install dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update
          apt-get install -y apt-transport-https ca-certificates gnupg software-properties-common wget
          wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null
          apt-add-repository 'deb https://apt.kitware.com/ubuntu/ noble main'
          apt-get update
          apt-get install -y cmake flex bison openmpi-bin libopenmpi-dev gfortran git python3 python3-numpy python3-pandas
