###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM   =   mpicomm

HYDRO     = nohydro
DENSITY   = nodensity
ENTROPY   = noentropy
MAGNETIC  = nomagnetic

GRAVITY   = nogravity
FORCING   = noforcing
VISCOSITY = noviscosity
EOS       = noeos
TESTFIELD =   testfield
