# Kishore: this file contains some machine-specific options too. I am leaving it
# as-is to avoid breaking the autotests on norlx51. Ideally, the machine-specific
# stuff below would be moved to a file in config/hosts, in which one can do
# %include gpu/astaroth
# %include gpu/transpile

%section Makefile
        GPU=gpu_astaroth
	MULTITHREADING=openmp
	RUNTIME_COMPILATION=on
	TRANSPILATION=on
	GENERATE_DSL_CODE=on
	MPICOMM=mpicomm
	CUDACXX=/usr/local/cuda-12.9/bin/nvcc
	LDFLAGS+=-lmpi_cxx -fsanitize=undefined -fstack-protector-all -no-pie -fstack-check
	CFLAGS=-DFUNDERSC=1 -mcmodel=large -fmax-errors=1 -Og -g -fsanitize=undefined -fsanitize=null -fstack-protector-all
        MODULE_PREFIX = __
        MODULE_INFIX  = _MOD_
        MODULE_SUFFIX = 
        CMAKE_BUILD_TYPE=Debug
        FFLAGS += -O -mcmodel=large -finit-real=sNaN -finit-integer=-99999999 -fcheck=bounds -fcheck=bits -fcheck=do -fcheck=pointer -fmax-errors=1 -fbacktrace -Og -g -fsanitize=null -fsanitize=undefined -fstack-protector-all -fstack-check
%endsection Makefile

