%section Makefile

    TORCHFORT_PATH=/scratch/project_2016901/sgiridha/torchfort_native_install/torchfort-install 
    HDF5_PATH=/scratch/project_2016901/sgiridha/hdf5_nvhpc_parallel 
    FFLAGS+=-O0 -g -traceback -I/scratch/project_2016901/sgiridha/hdf5_nvhpc_parallel/include
    LDFLAGS+=-Wl,--allow-shlib-undefined  -Wl,-rpath-link,$NVHPC_BASE/cuda/11.8/lib64  -Wl,-rpath-link,$NVHPC_BASE/comm_libs/11.8/nccl/lib   -L/scratch/project_2016901/sgiridha/libtorch/lib   -Wl,-rpath,/scratch/project_2016901/sgiridha/libtorch/lib     -Wl,-rpath,/scratch/project_2016901/sgiridha/torchfort_native_install/torchfort-install/lib     -L$CUDNN_PATH/lib     -Wl,-rpath,$CUDNN_PATH/lib     -L$CUSPARSELT_PATH/lib     -Wl,-rpath,$CUSPARSELT_PATH/lib     -L$NVHPC_BASE/cuda/11.8/lib64/stubs     -L$NVHPC_BASE/cuda/11.8/lib64     -Wl,-rpath,$NVHPC_BASE/cuda/11.8/lib64     -L$NVHPC_BASE/cuda/11.8/extras/CUPTI/lib64     -Wl,-rpath,$NVHPC_BASE/cuda/11.8/extras/CUPTI/lib64     -L$NVHPC_BASE/comm_libs/11.8/nccl/lib     -Wl,-rpath,$NVHPC_BASE/comm_libs/11.8/nccl/lib     -L$NVHPC_BASE/math_libs/11.8/lib64     -Wl,-rpath,$NVHPC_BASE/math_libs/11.8/lib64     -Wl,--no-as-needed -lnccl -lcudnn -lcusparseLt -Wl,--as-needed 

%endsection Makefile
%section runtime
    mpiexec = mpiexec
%endsection runtime
