%section Makefile

    PROJ_DIR = /projappl/project_2016901/$(USER)

    NVHPC_DIR ?= $(NVHPC)

    CUDA_LIB  = $(NVHPC)/cuda/lib64 
    NCCL_LIB  = $(NVHPC)/Linux_aarch64/26.3/comm_libs/nccl/lib

    TORCHFORT_PATH = $(PROJ_DIR)/torchfort-install
    LIBTORCH_PATH  = $(PROJ_DIR)/libtorch
    YAMLCPP_PATH   = $(PROJ_DIR)/yaml-cpp-install
    HDF5_PATH      = $(PROJ_DIR)/hdf5_nvhpc_parallel



    FFLAGS+=-O0 -g -traceback -I${HDF5_PATH}/include -I${TORCHFORT_PATH}/include
    CUDA_AWARE_MPI=OFF
    LDFLAGS += -Wl,--allow-shlib-undefined \
               -Wl,-rpath-link,$(CUDA_LIB) \
               -Wl,-rpath-link,$(NCCL_LIB) \
               -L$(HDF5_PATH)/lib -Wl,-rpath,$(HDF5_PATH)/lib \
               -L$(LIBTORCH_PATH)/lib -Wl,-rpath,$(LIBTORCH_PATH)/lib \
               -L$(TORCHFORT_PATH)/lib -Wl,-rpath,$(TORCHFORT_PATH)/lib \
               -L$(YAMLCPP_PATH)/lib64 -Wl,-rpath,$(YAMLCPP_PATH)/lib64 \
               -L$(CUDA_LIB) -Wl,-rpath,$(CUDA_LIB) \
               -L$(NCCL_LIB) -Wl,-rpath,$(NCCL_LIB) \
               -Wl,--no-as-needed -lnccl -ltorchfort -ltorchfort_fort -Wl,--as-needed

%endsection Makefile
%section runtime
    mpiexec = srun
%endsection runtime
